### ISSUE TITLE
upgrading to 1.78.0

### ISSUE THREAD

**Issue by souporserious** [CodinGame/monaco-vscode-api#100]
First, apologies for creating so many issues recently! I've been trying to keep up with all of the updates and am running into trouble with syntax highlighting not working when upgrading to the latest version 1.78.0. I noticed the initialization script changed which I've tried out in a [PR here](https://github.com/souporserious/next-monaco-vscode-api/pull/2/files#diff-4fdd2671edb1c99145194305a921c3b61d821c00bc24c246418f2c3b9601fee0), but I can't seem to get highlighting working. I'm currently getting the following error from `initializeVscodeExtensions`, which I'm not sure is the culprit:
<img width="1001" alt="image" src="https://user-images.githubusercontent.com/2762082/232698258-794d3234-a411-4b9d-bdb0-12c706f9e3db.png">

Since there were so many changes that landed in the last few PRs it's a little hard to determine what changed.

**Comment by CGNonofr** [comment]
I think you should wait for `initializeMonacoService` to end before calling `initializeVscodeExtensions`

**Comment by souporserious** [comment]
🤦 ack I totally forgot Promise.all wasn't sequential. I was trying to work around lack of top-level await support in Next.js and missed that. That seems to have fixed the issue, thank you!

The API surface has gotten a lot nicer btw! Kudos for all of the recent changes, I appreciate all of the help upgrading!

**Comment by souporserious** [comment]
Oh, had another question related to this update. Do I need to use `createModelReference` now? It looks like `createModel` still works from a quick test.

**Comment by CGNonofr** [comment]
`createModel` will still "work" as before

the issue is that createModelReference is called from a lot of places in the code (for instance to display the references inside the editor, to apply some changes and so on) and if you create you model by hands, no references will be created and createModelReference will fail

**Comment by souporserious** [comment]
Ok, good to know! 🙏 That's amazing that references will work 🤩
