### ISSUE TITLE
Crash when pack in react production environment.

### ISSUE THREAD

**Issue by Particle60** [CodinGame/monaco-vscode-api#102]
I'm using monaco-languageclient in a react appliation. It works well in development environment. Then I compiled the release version by `npm run build`. It will create a "build" folder for the result.
But when I mount this folder on our back-end server, the page will crashed.
The error is `"TypeError("Cannot call a class as a function");"`
After my debug, I found this is caused by babel plugin "[@babel/plugin-transform-runtime](https://babeljs.io/docs/babel-plugin-transform-runtime#helper-aliasing)". It is a default plugin for babel. It will add a fucntion `_classCallCheck` in every class to check class  inheritance.
The problem is that you overwright Services for monaco-editor.  In file "services2.js", you re-defined class "RawContextKey" and "ContextKeyDefinedExpr". 
The crash happends when checking `RawContextKey instanceof ContextKeyDefinedExpr`. For some reason, babel used `ContextKeyDefinedExpr` in monaco-editor to check.  They are different classes in different files, so the checking will fail.

So I added a patch in the following picture and the problem is solved.
I'm not sure my patch is perfect solution, I just want to give you a reference.

![image](https://user-images.githubusercontent.com/6045842/233062988-2a3a4e36-e337-4249-9f23-474cc9ac8f80.png)

**Comment by CGNonofr** [comment]
I'm aware this library doesn't work well with babel when trying to transform classes into functions

but [it is not required anymore](https://caniuse.com/?search=class) for a long time now so I may suggest to disable this transformation
