### ISSUE TITLE
v1.78.2 cannot export createModelReference.

### ISSUE THREAD

**Issue by KamiC6238** [CodinGame/monaco-vscode-api#104]
Hi, there is something different between the library README with the v1.78.2
![image](https://user-images.githubusercontent.com/23523595/233611077-5b2c1cb9-5b6e-422d-b030-c89ef7b349d2.png)

![image](https://user-images.githubusercontent.com/23523595/233610555-1b85a879-1607-4f3b-8fc3-a81dd5784d62.png)

**Comment by KamiC6238** [comment]
> ![image](https://user-images.githubusercontent.com/23523595/233610555-1b85a879-1607-4f3b-8fc3-a81dd5784d62.png)

**Comment by CGNonofr** [comment]
I don't speak that language, what does the error says?

**Comment by CGNonofr** [comment]
It does, are you sure you are using the last version?

**Comment by KamiC6238** [comment]
> 

Yes. 
![image](https://user-images.githubusercontent.com/23523595/233619350-e5a5b5ef-7a15-4bcc-9a91-a0c5ef4b8ced.png)

**Comment by CGNonofr** [comment]
I don't know, probably an issue related to pnpm? I can't reproduce.

Can you provide a project that reproduces it?
