### ISSUE TITLE
eager extensions activated console log

### ISSUE THREAD

**Issue by souporserious** [CodinGame/monaco-vscode-api#107]
Not a huge deal, but I'm curious if there is a way to suppress or fix the `INFO Eager extensions activated` logged to the console? I tried delaying the loading of instantiation code, but it seems to persist no matter what I try.

**Comment by CGNonofr** [comment]
You can override the `logService`

btw I realize we don't export the type, it's come in a next release

here's the interface;
```
{
    onDidChangeLogLevel: Event<LogLevel>;
    getLevel(): LogLevel;
    setLevel(level: LogLevel): void;
    trace(message: string, ...args: any[]): void;
    debug(message: string, ...args: any[]): void;
    info(message: string, ...args: any[]): void;
    warn(message: string, ...args: any[]): void;
    error(message: string | Error, ...args: any[]): void;
    /**
     * An operation to flush the contents. Can be synchronous.
     */
    flush(): void;
}
```

**Comment by souporserious** [comment]
Sorry, how would I override the `logService` exactly? I tried your other example as well, but it doesn't seem that `ILogService` is currently exported.

**Comment by CGNonofr** [comment]
You can import them directly from `monaco-editor/esm/vs/platform/log/common/log`

you can override it the same way you override other services:
```typescript
initialize({
  ...getXXXServiceOverride(),
  [ILogService.toString()]: new MyLogService()
})
```

but it's probably simpler to just use `setLevel`
