### ISSUE TITLE
1.76.6: No `DebugProtocol` found

### ISSUE THREAD

**Issue by hunger** [CodinGame/monaco-vscode-api#108]
I am trying to update my monaco-editor based on the versions found in [TypeFox/monaco-editor](https://github.com/TypeFox/monaco-languageclient/tree/main#monaco-editor-compatibility-table). These are the versions I ended up with in my `package.json`:

```
        "@types/vscode": "~1.76.0",
        "monaco-editor": "~0.36.1",
        "monaco-languageclient": "~5.0.1",
        "typescript": "^5.0.4",
        "vscode": "npm:@codingame/monaco-vscode-api@~1.76.6",
        "vscode-languageclient": "~8.1.0",
        "vscode-languageserver": "~8.1.0",
        "vscode-languageserver-protocol": "3.17.3"

```

Trying to build my code, I get errors about `DebugProtocol` not being known:

```
node_modules/vscode/dist/services.d.ts:17287:69 - error TS2503: Cannot find namespace 'DebugProtocol'.

17287     setExceptionBreakpointsForSession(session: IDebugSession, data: DebugProtocol.ExceptionBreakpointsFilter[]): void;
```

and similar ones. The file that is looking for this type seems to point here, but I might be misinterpreting the data.

Is that type indeed missing or am I doing something wrong?

**Comment by CGNonofr** [comment]
The types are maybe a little broken and miss some namespaces.

I'll try to have a look. In the meantime, you can probably enable `skipLibCheck`

**Comment by CGNonofr** [comment]
https://www.typescriptlang.org/tsconfig#skipLibCheck

you can add it in your tsconfig

**Comment by CGNonofr** [comment]
It will be fixed in https://github.com/CodinGame/monaco-vscode-api/pull/111

**Comment by kaisalmen** [comment]
@hunger and @CGNonofr I just realized I had `skipLibCheck` always set in projects dependent on `monaco-languageclient` and never noticed this issue. Next release of `monaco-languageclient` (today or tomorrow) based on `monaco-vscode-api` `1.78.5` will require it still, though.

**Comment by jhk-mjolner** [comment]
Why was this closed when the PR fixing it hasn't been merged yet? Has something else fixed the issue in the meantime?
