### ISSUE TITLE
Tree-mending breaks monaco-editor on Mac

### ISSUE THREAD

**Issue by kaisalmen** [CodinGame/monaco-vscode-api#112]
The following code (https://github.com/microsoft/vscode/blob/main/src/vs/workbench/browser/parts/editor/editor.contribution.ts#L326-L337) breaks the demo and any monaco-editor on Mac once tree-mending was invoked. It works fine on Linux and Windows as the code path below is not taken. Quickest way to re-produce on a non-Mac is to replace `isMacintosh` with `true`. As you can see below I built a virtual Mac with Qemu/KVM (thanks to https://github.com/kholia/OSX-KVM) on Ubuntu/WSL (nested virtualization!) to re-produce the issue and find and understand the root-cause. 🤯 

```javascript
if (isMacintosh) {
    MenuRegistry.appendMenuItem(MenuId.TouchBarContext, {
        command: { id: NavigateBackwardsAction.ID, title: NavigateBackwardsAction.LABEL, icon: { dark: ( FileAccess.asFileUri('vs/workbench/browser/parts/editor/media/back-tb.png')) } },
        group: 'navigation',
        order: 0
    });
    MenuRegistry.appendMenuItem(MenuId.TouchBarContext, {
        command: { id: NavigateForwardAction.ID, title: NavigateForwardAction.LABEL, icon: { dark: ( FileAccess.asFileUri('vs/workbench/browser/parts/editor/media/forward-tb.png')) } },
        group: 'navigation',
        order: 1
    });
}
```
Tree mending introduced changes `network.js` that makes them use `asFileUri` and `asBrowserUri` which both expect `window.monacoRequire` to be existent. This above code path is taken as soon as you import
```
import * as monaco from 'monaco-editor/esm/vs/editor/editor.api'
```
Importing `assets.js` manually beforehand is a workaround, but it is not a fix.

<del>What I don't yet understand who should be responsible for defining this function in vscode itself (I mean the application).</del>. Ok, it relies on `require`/`NodeRequire` to be present.
Must this library embed monaco-editor completely, so we can ensure pre-conditions or lifecycle or should something extra code be added to treemending patch?

![image](https://github.com/CodinGame/monaco-vscode-api/assets/21079138/43218610-46a0-4839-bc09-5338f28fbf46)

**Comment by CGNonofr** [comment]
It's not related to the treemending I think, the crashing code is inside this library dist folder

It's already fixed in the next open PRs, I've backported the changed into https://github.com/CodinGame/monaco-vscode-api/pull/114

feel free to approve and merge if it's ok for you

**Comment by kaisalmen** [comment]
> It's not related to the treemending I think, the crashing code is inside this library dist folder

The treemending patch brings back the code in `network.js` in monaco-editor that now produces the error. Previously this was handled by the polyfill if I understand it correctly.
