### ISSUE TITLE
Broken contract for editor model

### ISSUE THREAD

**Issue by BusinessDuck** [CodinGame/monaco-vscode-api#117]
New contract is blocking some cases with language id

**Classic way:** 

```
monaco.editor.createModel(source, langueageId);
```

**New way:**

```
const modelRef = await createModelReference(monaco.Uri.file('/tmp/test.js'), source)
```

How i can determine language id? 
Why the contact of `createModelReference` is different from `monaco.editor.createModel`?

Also please use uri as non required argument like in[ normal contract](https://microsoft.github.io/monaco-editor/typedoc/functions/editor.createModel.html).

**Comment by CGNonofr** [comment]
`createModelReference` is an internal api of vscode, the language is detected from the file name and content.

If the detection failed, you can still use`monaco.editor.setModelLanguage` on the returned model

> Also please use uri as non required argument like in[ normal contract](https://microsoft.github.io/monaco-editor/typedoc/functions/editor.createModel.html).

The point of this method is to create a reference to a model via a path. generating a random path here (what monaco.editor.createModel is doing when no uri is provided) has no point. You can still use monaco.editor.createModel is such cases

**Comment by BusinessDuck** [comment]
`createModelReference` contract is designed by vscode, right?

**Comment by CGNonofr** [comment]
What do you mean?

**Comment by CGNonofr** [comment]
Yes, I've just added the `source` parameter which write the file on the virtual filesystem before calling the internal api
