### ISSUE TITLE
Wasm import causes library to break with Vite

### ISSUE THREAD

**Issue by TaeHagen** [CodinGame/monaco-vscode-api#122]
When using this library with Vite it crashes stating `[vite] Internal server error: "ESM integration proposal for Wasm" is not supported currently. Use vite-plugin-wasm or other community plugins to handle this.`

The problematic line is: https://github.com/CodinGame/monaco-vscode-api/blob/4ab2407733597b8a543331c4f6687650b57ce241/src/service-override/textmate.ts#L11

Vite interprets this as a WASM ESM module and throws an error. Attempting to install `vite-plugin-wasm` results in errors about unresolved imports as the WASM file is not an ESM module. Appending a `?url` to the link causes the import to instead resolve to the URL when using Vite ([docs](https://vitejs.dev/guide/features.html#static-assets)) and the library works as intended.

I'm not sure how you would want to handle Vite, but as far as I can tell there isn't any other way to fix this other than appending a `?url`. At this point I have to add it manually in my node_modules which is really annoying.

This is a really useful library and I'm looking forward to using it in my Vite projects!

**Comment by CGNonofr** [comment]
Fyi, the demo here uses vite as well.

You need to add `assetsInclude: ['**/*.wasm']` un you config

**Comment by TaeHagen** [comment]
Thanks! I guess I need to look at the vite documentation again :)

**Comment by CGNonofr** [comment]
You're right, it's not mentionned! :) feel free to contribute to the documentation ;)
