### ISSUE TITLE
TypeError: overflowWidgetsDomNode.appendChild is not a function

### ISSUE THREAD

**Issue by jhk-mjolner** [CodinGame/monaco-vscode-api#129]
I'm trying to use the configuration option `overflowWidgetsDomNode` in my monaco editor. But I get the error `TypeError: overflowWidgetsDomNode.appendChild is not a function`. 

I'm using monaco-vscode-api via monaco-languageclient version 6.0.2, which depends on monaco-vscode-api version 1.78.8, but I believe I've found the cause of the issue in the newest code as well: https://github.com/CodinGame/monaco-vscode-api/blob/f82fbfd0200d448e63da9d844c0ad3699fb4d9d7/src/monaco.ts#L86-L88
I believe the `overflowWidgetsDomNode` should be passed around the `computeConfiguration()` call like `ariaContainerElement` is, as the `computeConfiguration()` call seems incompatible with dom nodes.

When breakpointing into the above linked code, at line 88, `options.overflowWidgetsDomNode` is the correct dom node, but `computedOptions.overflowWidgetsDomNode` is an otherwise empty object, containing only an angular-specific value `__ngContext__: 8` (I'm using Angular), and this is the object it later tries to call `appendChild()` on.

**Comment by CGNonofr** [comment]
If I understand properly, the fix is quite simple, do you mind open a PR?
