### ISSUE TITLE
Bundle size when using webpack

### ISSUE THREAD

**Issue by char0n** [CodinGame/monaco-vscode-api#136]
Hi again,

When updating from `v1.76.7` to `v1.79.6` I've noticed that the JavaScript bundle size of this library when built with webpack@5 bumped from `1.05 MB` to `1.55 MB`. It's half of megabyte of additional code. I've started to hit the JavaScript memory limits. I know it can be extended, but I'm looking for a way how to use this library only with minimal code required to integrate with `monaco-editor`.

Here are all the imports I currently use:

```js
import { initialize as initializeExtensions } from 'vscode/extensions';
import { StandaloneServices, IStorageService } from 'vscode/services';
import { languages as vscodeLanguages } from 'vscode';
```

On `vscodeLanguages` I call the following methods:

- createDiagnosticCollection
- register*Provider
- setLanguageConfiguration

---

I've tried to `hack` this library and set `"sideEffects": false` in `package.json` to allow webpack@5 to tree-shake as much as possible. I've created the new `api1.js` file and mapped it via `package.json` exports fields:

**api1.js**
```
import create$5 from './vscode-services/languages.js';
import { getDefaultExtension } from './default-extension.js';

export const languages = create$5(getDefaultExtension)
```

Then I use it in following way:

```js
import { languages as vscodeLanguages } from 'vscode/api1';
```

Of course it didn't help and I'm getting:

![image](https://github.com/CodinGame/monaco-vscode-api/assets/193286/a57ac762-c51c-4fb6-a9f4-fe94dea9b6cc)

Any advice please?

---

**Memory limits hit:**

[2735:0x73a8570]   271065 ms: Mark-Compact 2041.4 (2087.3) -> 2038.2 (2088.1) MB, 2524.44 / 0.00 ms  (average mu = 0.079, current mu = 0.011) allocation failure; scavenge might not succeed
[2735:0x73a8570]   274485 ms: Mark-Compact 2042.2 (2088.1) -> 2039.1 (2097.1) MB, 3408.39 / 0.00 ms  (average mu = 0.037, current mu = 0.003) allocation failure; scavenge might not succeed

<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0xc925e0 node::Abort() [/opt/hostedtoolcache/node/20.3.1/x64/bin/node]
 2: 0xb6d969  [/opt/hostedtoolcache/node/20.3.1/x64/bin/node]
 3: 0xeb0fe0 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [/opt/hostedtoolcache/node/20.3.1/x64/bin/node]
 4: 0xeb12c7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [/opt/hostedtoolcache/node/20.3.1/x64/bin/node]
 5: 0x10c2935  [/opt/hostedtoolcache/node/20.3.1/x64/bin/node]
 6: 0x10da7b8 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/opt/hostedtoolcache/node/20.3.1/x64/bin/node]
 7: 0x10b08d1 v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/opt/hostedtoolcache/node/20.3.1/x64/bin/node]
 8: 0x10b1a65 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/opt/hostedtoolcache/node/20.3.1/x64/bin/node]
 9: 0x108efd6 v8::internal::Factory::NewFillerObject(int, v8::internal::AllocationAlignment, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/opt/hostedtoolcache/node/20.3.1/x64/bin/node]
10: 0x[14](https://github.com/swagger-api/swagger-editor/actions/runs/5248386550/jobs/9479797723#step:10:15)e9e06 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/opt/hostedtoolcache/node/[20](https://github.com/swagger-api/swagger-editor/actions/runs/5248386550/jobs/9479797723#step:10:21).3.1/x64/bin/node]
11: 0x7fb9e3e99ef6
```

**Comment by CGNonofr** [comment]
The library got bigger because it implements more and more of the vscode api, and it requires to pull more extHost/mainThread classes from vscode. And it's going to get even bigger.

While vscode services are split and optional in this libraries, the extHost and mainThread are all included no matter what, which explains the increased size.

I guess something can be done about it. Let this issue open, I'll have a look at it eventually

**Comment by CGNonofr** [comment]
Can you have a look at the 1.79.7-next.2?

To have the same behavior as before, you need to import `vscode/ext-hosts/all`

but the fun part if that you can now only imports the parts you need, see the description of https://github.com/CodinGame/monaco-vscode-api/pull/137

**Comment by char0n** [comment]
Thanks I'll check this out ASAP and will let you know about the results ;]

**Comment by char0n** [comment]
Hi @CGNonofr,

I'm not sure I understand the `vscode/ext-hosts/all`. There is not such export. There is also very minial info in #137 how to proceed with this.

**Comment by char0n** [comment]
Right, I can see it now: https://github.com/CodinGame/monaco-vscode-api/pull/137/files#diff-8abc69608b75ad164e54ebd42e911508c55afa8ebf5a2732d27b3bae3e76e0d5R29

**Comment by char0n** [comment]
Here is the minimal combination of `ext-hosts` imports that work for me:

```js
import 'vscode/ext-hosts/commands';
import 'vscode/ext-hosts/configuration';
import 'vscode/ext-hosts/documentsAndEditors';
import 'vscode/ext-hosts/filesystem';
import 'vscode/ext-hosts/localization';
import 'vscode/ext-hosts/telemetry';
import 'vscode/ext-hosts/terminal';
import 'vscode/ext-hosts/workspace';
import 'vscode/ext-hosts/languageFeatures';
```

Now I can further remove following ones and see only warnings in browser console:

```js
import 'vscode/ext-hosts/localization';
import 'vscode/ext-hosts/telemetry';
import 'vscode/ext-hosts/terminal';
```

![image](https://github.com/CodinGame/monaco-vscode-api/assets/193286/2a77f88f-7054-4601-ad46-1ed539d8ff6a)


**Can this warnings be get rid of?**

---

What ever else I remove I'll get into red errors in browser console.

**Comment by char0n** [comment]
I've also noticed that v1.80.0 doesn't contain `vscode/ext-hosts/*` export. It was introduced in https://github.com/CodinGame/monaco-vscode-api/commit/d509e3dddb2efe42d7a7730cc330c23fe03581bb but has been removed again in https://github.com/CodinGame/monaco-vscode-api/commit/55de45a5d1ac3b92c72f1c99011a52261699926e.

**Comment by char0n** [comment]
Some new measurements:

- v1.76.7 -> v1.79.6 - size increased from 1.05 MB to 1.55 MB
- v1.79.6 -> v1.80.0 - size increased from 1.55 MB to 2.1 MB

**Comment by CGNonofr** [comment]
You're right, unfortunately, it was not compatible with the worker ext-host and was rollbacked.

I'm still open to ways of reducing bundle size for users who don't need all the features, but I'm out of ideas

**Comment by CGNonofr** [comment]
I'm not sure how it can help, can you explain a little bit more?

**Comment by char0n** [comment]
> I'm not sure how it can help, can you explain a little bit more?

Live for example stuff with `ext-hosts`. By default all ex-hosts are imported somewhere within VSCode API.

```js
import 'vscode/ext-hosts/commands';
import 'vscode/ext-hosts/configuration';
import 'vscode/ext-hosts/documentsAndEditors';
import 'vscode/ext-hosts/filesystem';
import 'vscode/ext-hosts/localization';
import 'vscode/ext-hosts/telemetry';
import 'vscode/ext-hosts/terminal';
import 'vscode/ext-hosts/workspace';
import 'vscode/ext-hosts/languageFeatures';
```

If I knew that I didn't need most of them I can configure my webpack `resolve.alias` to resolve these unneeded imports f to empty file. This would work as long as the import can really be optional and not necessary for VSCode API to function. Hope it make sense.

If this would be something that could work, we would just document which files in the npm distributions package can be dropped by webpack.

**Comment by CGNonofr** [comment]
These files don't exist anymore, they were part of this library

in the VSCode code base, everything is mixed up and there is no easy automatic way to ignore some parts of the code. Also it uses injection a lot so knowing what depends on what can't be done statically. And the hardest part is that there is pairs of classes: MainThread and ExtHost that should stay in pair, one in the app and the other in the worker, and we can't have one without the other
