### ISSUE TITLE
Exposing VSCode Types

### ISSUE THREAD

**Issue by CompuIves** [CodinGame/monaco-vscode-api#138]
First I'd like to say that this project is incredibly impressive. I'm amazed that you've been able to create an _extensible_ package from the VSCode codebase and expose it as a library.

I'm currently exploring this library, and I'm wondering about the service override story. I'm trying to override a service with a custom implementation, but in some cases I need to use VSCode types that are currently not exposed by `monaco-vscode-api`. Specifically, I'm now looking how I can override `IOutputService`, but the interface is not available from the types alone.

So I'm wondering, would it be possible to expose the types from VSCode in the package as well? That would make it easier to override services with custom ones, without having to pull in the VSCode codebase.

**Comment by CGNonofr** [comment]
Thanks for the heartwarming introduction :)

Regarding the types, we're already doing it, in [src/services](https://github.com/CodinGame/monaco-vscode-api/blob/main/src/services.ts) but the OutputService is missing indeed, feel free to issue a PR :)
