### ISSUE TITLE
Access to `IBulkEditingService`

### ISSUE THREAD

**Issue by CompuIves** [CodinGame/monaco-vscode-api#144]
Heya! Here I am again. Today we did a first deploy of CodeSandbox using `monaco-vscode-api` 🎉 . I'm super excited to explore more integrations (you can check it here: https://vite.react.new).

One feature I've been wanting to add is bulk editing, for that I need the `IBulkEditingService` from VSCode. I've tested enabling this service by fetching it from the `viewOverride`, kind of like this:

```
const viewsOverride = getViewsOverride();

initialize({
  // other servics
  [IBulkEditingService.toString()]: viewsOverride[IBulkEditingService.toString()]
})

```

But it would be nice if we could get it without pulling in everything from views.

I'm happy to open a PR for this, but I was wondering what your preferred approach would be. Should we add this to an existing service override (like editor?), or should I create a new override specifically for bulk editing?

**Comment by CGNonofr** [comment]
Awesome!

There is already some service overrides that require others. You can just create a new module and call it from views (as for the layout services).

I agree views contains a lot of services, feel free to split it as needed
