### ISSUE TITLE
Handling "openEditor" for editors that are already opened

### ISSUE THREAD

**Issue by CompuIves** [CodinGame/monaco-vscode-api#148]
The `SimpleEditorService` accepts an `openEditor` argument that we can use to open new editors if they aren't opened yet. This works well for new editors, but if the editor is already opened, we don't get an event.

If we have the scenario that we have two tabs open (`a` and `b`). And we do a "Go to Definition" which should lead us to tab `b`, nothing happens currently. In the `wrapOpenEditor` the `b` code editor is put into focus (`.focus()`) and scrolled into view, but in our case that's not sufficient as it's hidden behind an editor tab.

So I'm thinking, would it be a good idea if either:

1. The `wrapOpenEditor` will still call `openEditor`, even if the `modelEditor` already exists
2. We can supply a second callback `navigateEditor`, which will be called when a `modelEditor` is already opened

**Comment by CGNonofr** [comment]
Actually, you're not really expected to have an editor per tab and hide it, but having a single editor and switch the model instead. It's better un term or performances and prevent such issues

**Comment by CompuIves** [comment]
It's a good point, it will take some refactoring on our side to do this. In the meantime I'm using a custom editor service to handle it!
