### ISSUE TITLE
Themes are not loading

### ISSUE THREAD

**Issue by VVeaz** [CodinGame/monaco-vscode-api#155]
Hello :).

Recently I upgraded 

monaco-editor 0.34.1 to 0.40.0, 
monaco-language-client from 4.0.3 to 6.2.0 
codingame/monaco-vscode-api [named as vscode] 1.69.13 to 1.80.0.

After adjusting my code, I was left with one problem: Themes are not loading.
This applies to both - setting theme for the first time for editor (in createConfiguredEditor) and using the editor.setTheme(theme) method.

From what I noticed in both the old and the new version, when setting the theme, you get to the monaco-editor\esm\vs\editor\standalone\browser\standaloneCodeEditor.js file, exactly to this fragment of code:

```
if (typeof options.theme === 'string') {
    themeService.setTheme(options.theme);
}
```

In the old version `themeService` is an object of class `StandaloneThemeService` from file` monaco-editor\esm\vs\editor\standalone\browser\standaloneThemeService.js.` It seems that in the new version this file still exists but is not used.

In the new version `themeService` is an object of the `StandaloneWorkbenchThemeService `class from the` vscode\dist\service-override\theme.js` file

The services are set in the `monaco-editor\esm\vs\platform\instantiation\common\instantiationService.js` file using the `_createInstance` method (in both the old and the new version).

Probably this change is intentional, but I suspect that something is missing (maybe in my code), some complement of themes, because following `themeService.setTheme(options.theme)` from the `StandaloneWorkbenchThemeService` class from the file `vscode\dist\service-override\theme.js` I get to the `internalSetColorTheme` method in `vscode\dist\vscode\vs\workbench\services\themes\browser\workbenchThemeService.js`

`let themeData = this.colorThemeRegistry.findThemeById(themeId);`

here` themeData` is undefined because looking at `findThemeById `method from `ThemeRegistry` class from file `vscode\dist\vscode\vs\workbench\services\themes\common\themeExtensionPoints.js`
there is fragment of code

` const allThemes = this.getThemes();`

where
`allThemes` is an empty array.

Here it seems to me that this array should be filled with some basic themes like vs, vs-dark, etc. Similarly to how` _knownThemes` is done in `StandaloneThemeService`.

        this._knownThemes = new Map();
        this._knownThemes.set(VS_LIGHT_THEME_NAME, newBuiltInTheme(VS_LIGHT_THEME_NAME));
        this._knownThemes.set(VS_DARK_THEME_NAME, newBuiltInTheme(VS_DARK_THEME_NAME));
        this._knownThemes.set(HC_BLACK_THEME_NAME, newBuiltInTheme(HC_BLACK_THEME_NAME));
        this._knownThemes.set(HC_LIGHT_THEME_NAME, newBuiltInTheme(HC_LIGHT_THEME_NAME));

Maybe someone had a similar problem and knows a solution?

**Comment by CGNonofr** [comment]
What theme are you trying to apply? are you registering your own theme?

**Comment by CGNonofr** [comment]
If you use the theme service override, you now need to use vscode themes, not monaco themes anymore

It can be done by using the vscode default themes (importing `vscode/default-extensions/theme-defaults`) and setting the theme to `Default Dark+` for instance

**Comment by VVeaz** [comment]
Thank you very much, importing vscode/default-extensions/theme-defaults solves my problem.
