### ISSUE TITLE
Error: [invokeFunction] unknown service 'explorerService'

### ISSUE THREAD

**Issue by AXeL-dev** [CodinGame/monaco-vscode-api#157]
Hello,

I'm getting an error when triggering the `redo` action using the following line of code:

```ts
editor.trigger('keyboard', 'redo', {});
```

The error message is the following:

![Screen Capture_select-area_20230804110715](https://github.com/CodinGame/monaco-vscode-api/assets/30635693/51bd3de1-4895-4a93-997e-65a6dd29cd5e)

Below my packages versions:
- `monaco-editor: 0.37.1`
- `monaco-vscode-api: 1.78.8`
- `monaco-languageclient: 6.0.3`

After some investigation, it seems like the error is coming from the following piece of code:

![Screen Capture_select-area_20230803230741](https://github.com/CodinGame/monaco-vscode-api/assets/30635693/1c54a9d4-4c22-4359-b5ec-c04b33d2b57e)

I thought to override the `ExplorerService` to bypass the error still i didn't succeed, it seems like there is no override/implementation yet for that service, am i right?

Any help is welcome, thank you!

**Comment by CGNonofr** [comment]
Can you try with the last version of this lib/monaco-editor?

**Comment by kaisalmen** [comment]
Hi @AXeL-dev there is a next version is available (https://github.com/TypeFox/monaco-languageclient/issues/512):
https://www.npmjs.com/package/monaco-languageclient/v/6.3.0-next.1
that uses `monaco-vscode-api` `1.80.1-next.0` and `monaco-editor` `0.40.0`

**Comment by kaisalmen** [comment]
@CGNonofr and @AXeL-dev There now is a Draft PR: https://github.com/TypeFox/monaco-languageclient/pull/513
I need to update documentation, but then it is ready for review.

**Comment by AXeL-dev** [comment]
@kaisalmen Actually, it was due to a missing dependency, i fixed it by installing it:

```ts
npm i @vscode/vscode-languagedetection
```

**Comment by AXeL-dev** [comment]
@CGNonofr @kaisalmen All good now! the redo works correctly with version `6.3.0-next.1`.

Thank you so much for the help!
