### ISSUE TITLE
Problems with brackets (coloring and autoclosing)

### ISSUE THREAD

**Issue by VVeaz** [CodinGame/monaco-vscode-api#159]
Hello 
Recently I upgraded

monaco-editor 0.34.1 to 0.40.0,
monaco-language-client from 4.0.3 to 6.2.0
codingame/monaco-vscode-api [named as vscode] 1.69.13 to 1.80.0.

I noticed that the **brackets do not close automatically** and also **do not color** pairs (the lack of coloring pair bracket was the main reason why I bumped the packages - there was bug in 0.34.1 in monaco-editor,  looking at the playground in 0.40.0 it doesn't exist anymore)

I don't do any special things when creating an editor:
```
editorRef.current = createConfiguredEditor(ref.current, {
			model: model,
			glyphMargin: true,
			lightbulb: {
				enabled: true
			},
			automaticLayout: true,
			fixedOverflowWidgets: true,
			theme: theme,
			value: defaultCode,
			'semanticHighlighting.enabled': true,
			'bracketPairColorization.enabled': true,
			autoClosingBrackets: "always",
			readOnly: isBlocked,
			language: 'lua'
		});
```
I also use luaLSP - https://github.com/LuaLS/lua-language-server

Before this issue  I had another problem - themes was not loading. This problem was solved  thanks to user @CGNonofr in https://github.com/CodinGame/monaco-vscode-api/issues/155 who suggested adding an import `import 'vscode/default-extensions/theme-defaults';`.
Following the solution to that problem, I've added import - `import 'vscode/default-extensions/lua'` but it didn't help.

I've tried to debug it, the only thing I found is that in the `monaco-editor\esm\vs\editor\common\model\bracketPairsTextModelPart\bracketPairsTree\bracketPairsTree.js`  in `collectBrackets` method, `node.kind` is always `0` (`AstNodeKind.Text`)  or `4` (`AstNodeKind.List`) , never `1`,`2`,`3` (`AstNodeKind.Bracket` , `AstNodeKind.Pair`, `AstNodeKind.UnexpectedClosingBracket`), so it may looks like `parseList` from `monaco-editor\esm\vs\editor\common\model\bracketPairsTextModelPart\bracketPairsTree\parser.js` is not working, but looking  at the playground in 0.40.0 this is ok.

In general, it seems to me that coloring is incomplete, comparing, for example, how it works in VSC.
VSC: 
![image](https://github.com/CodinGame/monaco-vscode-api/assets/36280384/02e0149a-af84-4c67-87df-11c2c2dd8258)

My custom editor:
![image](https://github.com/CodinGame/monaco-vscode-api/assets/36280384/a93744f2-c5d3-416f-a98f-eec65748227c)

Maybe someone has an idea to solve this problem?

**Comment by VVeaz** [comment]
Thank you very much for your answer.

I've added `updateUserConfiguration`

```
updateUserConfiguration(`{				
				"editor.autoClosingBrackets": "always",
				"editor.fontSize": 12,
				"[lua]": {
				  "editor.defaultFormatter": "sumneko.lua",
				  "editor.fontSize": 30,
				  "editor.semanticHighlighting.enabled": true,
				  "editor.bracketPairColorization.enabled": true,
				  "editor.autoClosingBrackets": "always"
				}
			  }`)
```

**Unfortunately, the coloring remained as it was.** The method itself works because the font size has changed.
Before calling `updateUserConfiguration` I have
```
await initServices({				
				enablePreferencesService: true,
				enableSnippetsService: true,
				enableThemeService: true,
				enableTextmateService: true,
				enableModelService: true,
				enableFilesService:true,
				configureEditorOrViewsServiceConfig: {
					enableViewsService: false,
					useDefaultOpenEditorFunction: true,
				},
				configureConfigurationServiceConfig: {
					defaultWorkspaceUri: `${props.data}`,
					
				},
				enableLanguagesService: true,
				enableKeybindingsService: true,
				enableQuickaccessService: true,
				debugLogging: true,
			});
```

Method `initServices` is from `monaco-languageclient` (https://github.com/TypeFox/monaco-languageclient/blob/0de4ffead7cbd831069ae083af14bf5cb6a45775/packages/client/src/monaco-vscode-api-services.ts#L27) and uses `vscode/services`.

Do you have any idea what I'm doing wrong?

**Comment by CGNonofr** [comment]
`bracketPairColorization` is working now, right?

regarding the semantic tokens, which theme are you using? are you importing 'vscode/default-extensions/theme-defaults'? do you use `Visual Studio Dark` instead of `Default Dark+` ? (the second one extends the first one by adding semantic token colors)

**Comment by VVeaz** [comment]
_bracketPairColorization is working now, right?_
- Nope. This is how  it looked like:
![image](https://github.com/CodinGame/monaco-vscode-api/assets/36280384/e874d848-30c6-4888-a1b3-9fc3475d223e)

Yes, I import this -> `import 'vscode/default-extensions/theme-defaults';`
Then I set 'vs-dark' or 'vs'.

Now I set 'Default Dark+' as you suggested me. I've also tried that:
```
updateUserConfiguration(`{				
				"editor.autoClosingBrackets": "always",
				"editor.fontSize": 12,
				**"workbench.colorTheme": "Default Dark+",**
				"[lua]": {
				  "editor.defaultFormatter": "sumneko.lua",
				  "editor.fontSize": 30,
				  "editor.semanticHighlighting.enabled": true,
				  "editor.bracketPairColorization.enabled": true,
				  "editor.autoClosingBrackets": "always",
				  **"workbench.colorTheme": "Default Dark+"**
				}
			  }`)
			  ```
 In both cases, the effect is as follows:
 
![image](https://github.com/CodinGame/monaco-vscode-api/assets/36280384/c5797d41-bd3b-4c59-93d2-5c8bad078d9f)

So it's better (thank you again) but still different than in VSC with the same configuration (my editor doesn't color brackets in pairs)
![image](https://github.com/CodinGame/monaco-vscode-api/assets/36280384/9b464e7f-0376-4d7d-96ab-23602e36ae98)

**I also still have a problem with the brackets not closing automatically.**

My editor:


![2023-08-09_13h52_06](https://github.com/CodinGame/monaco-vscode-api/assets/36280384/a1832059-7e10-4739-bcf8-242b73ee4665)

VSC:

![2023-08-09_13h15_28](https://github.com/CodinGame/monaco-vscode-api/assets/36280384/1dfe7f94-ad37-4b69-ae8f-8e7398bfb4ba)

Do you have any other idea?

**Comment by CGNonofr** [comment]
> still different than in VSC with the same configuration

I'm lost, the only difference I notice (except bracket pairs) is the `nil` in blue/purple ; but in the screenshot above, it was blue in your editor

> I also still have a problem with the brackets not closing automatically.

there is a `editor.autoClosingBrackets` settings

btw, setting the color theme per language doesn't make much sense

**Comment by VVeaz** [comment]
Yes, thank you, I notice that `nil` is blue when sumneko lua lsp is disabled. 
When sumneko lua lsp is enabled it is purple (lsp somehow gives its coloring,  I don't know why its different than in VSC)
here lsp was disabled. -> 
![image](https://github.com/CodinGame/monaco-vscode-api/assets/36280384/83d7dca6-cb00-4540-9fbc-06aba683469d)

here lsp was enabled.->
![image](https://github.com/CodinGame/monaco-vscode-api/assets/36280384/136d6384-e1e6-4e5f-a491-6bba43c747b2)

I might report this as a bug in Lualsp but more important to me is the automatic closing of brackets and coloring the brackets in pairs.
I have `editor.autoClosingBrackets` set on `always` but unfortunately the brackets don't close.

**Comment by CGNonofr** [comment]
> I have editor.autoClosingBrackets set on always but unfortunately the brackets don't close.

Are you able to reproduce in the demo of this repo?

**Comment by VVeaz** [comment]
I want to try to do it. Unfortunately, when executing the command `npm ci` I get an error

```
> monaco-vscode-api-demo@0.0.0 postinstall
> monaco-treemending

node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '...\monaco-vscode-api-1.80.0\dist\monaco-treemending.js' imported from ...\monaco-vscode-api-1.80.0\monaco-treemending.js
    at new NodeError (node:internal/errors:399:5)
    at finalizeResolution (node:internal/modules/esm/resolve:231:11)
    at moduleResolve (node:internal/modules/esm/resolve:850:10)
    at defaultResolve (node:internal/modules/esm/resolve:1058:11)
    at nextResolve (node:internal/modules/esm/hooks:654:28)
    at Hooks.resolve (node:internal/modules/esm/hooks:309:30)
    at ESMLoader.resolve (node:internal/modules/esm/loader:312:26)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:172:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```
In fact, I can't see the dist folder.

I've tried to removed it from package.json, then npm ci goes fine (after adding set beforeNODE_OPTIONS) but npm start has no result:
![image](https://github.com/CodinGame/monaco-vscode-api/assets/36280384/e92e08ba-5dbf-45ca-a26b-4c1ce4b7d266)

, npm run start:debug has error `Error: Failed to resolve entry for package "vscode". The package may have incorrect main/module/exports specified in its package.json.`

**Comment by CGNonofr** [comment]
The demo only works if the main project is built:
```
npm ci
npm run build
cd demo
npm ci
npm start
```

**Comment by VVeaz** [comment]
Thank you for this tip. 
I'm currently facing difficulties running `npm ci` on Windows; unfortunately, I haven't been successful so far. I've attempted to make minor adjustments to the package.json file for Windows, but I've encountered an impasse due to the following error:

```
Assertion failed: bad export type for `tree_sitter_tsx_external_scanner_create`: undefined
Unhandled Rejection at: Promise Promise {
  <rejected> RuntimeError: abort(Assertion failed: bad export type for `tree_sitter_tsx_external_scanner_create`: undefined). Build with -s ASSERTIONS=1 for more info.
      at se (C:\Users\userName\AppData\Local\Temp\tmp.JxT4ZELAF1\node_modules\web-tree-sitter\tree-sitter.js:1:6761)
      at k (C:\Users\userName\AppData\Local\Temp\tmp.JxT4ZELAF1\node_modules\web-tree-sitter\tree-sitter.js:1:4462)
      at Pe (C:\Users\userName\AppData\Local\Temp\tmp.JxT4ZELAF1\node_modules\web-tree-sitter\tree-sitter.js:1:12582)
      at c (C:\Users\userName\AppData\Local\Temp\tmp.JxT4ZELAF1\node_modules\web-tree-sitter\tree-sitter.js:1:10613)
      at C:\Users\userName\AppData\Local\Temp\tmp.JxT4ZELAF1\node_modules\web-tree-sitter\tree-sitter.js:1:10879
      at async C:\Users\userName\AppData\Local\Temp\tmp.JxT4ZELAF1\node_modules\@vscode\l10n-dev\dist\main.js:254:10
      at async C:\Users\userName\AppData\Local\Temp\tmp.JxT4ZELAF1\node_modules\@vscode\l10n-dev\dist\main.js:243:22
} reason: RuntimeError: abort(Assertion failed: bad export type for `tree_sitter_tsx_external_scanner_create`: undefined). Build with -s ASSERTIONS=1 for more info.
    at se (C:\Users\userName\AppData\Local\Temp\tmp.JxT4ZELAF1\node_modules\web-tree-sitter\tree-sitter.js:1:6761)
    at k (C:\Users\userName\AppData\Local\Temp\tmp.JxT4ZELAF1\node_modules\web-tree-sitter\tree-sitter.js:1:4462)
    at Pe (C:\Users\userName\AppData\Local\Temp\tmp.JxT4ZELAF1\node_modules\web-tree-sitter\tree-sitter.js:1:12582)
    at c (C:\Users\userName\AppData\Local\Temp\tmp.JxT4ZELAF1\node_modules\web-tree-sitter\tree-sitter.js:1:10613)
    at C:\Users\userName\AppData\Local\Temp\tmp.JxT4ZELAF1\node_modules\web-tree-sitter\tree-sitter.js:1:10879
    at async C:\Users\userName\AppData\Local\Temp\tmp.JxT4ZELAF1\node_modules\@vscode\l10n-dev\dist\main.js:254:10
    at async C:\Users\userName\AppData\Local\Temp\tmp.JxT4ZELAF1\node_modules\@vscode\l10n-dev\dist\main.js:243:22
The following tasks did not complete: editor-distro
Did you forget to signal async completion?
error Command failed with exit code 1.
```

 which is hard for me to do anything with.

**Comment by VVeaz** [comment]
After upgrade
monaco-editor to 0.41.0,
monaco-language-client 6.4.0 (to connect with lua lsp by Websocekt)
codingame/monaco-vscode-api [named as vscode] 1.81.0.
I have to add @vscode/vscode-languagedetection in version 1.0.22 (to npx webpack even work)
and **coloring of pair bracket is working now. Autoclosing of brakcket is working now too.**
Thanks.
