### ISSUE TITLE
registerFileUrl with existing data?

### ISSUE THREAD

**Issue by kaisalmen** [CodinGame/monaco-vscode-api#161]
I stumbled upon one thing yesterday. I am currently adapting [monaco-editor-wrapper](https://github.com/TypeFox/monaco-components/tree/mlc-630) to the latest releases (WIP).

Instead of `registerExtensionFile` which required a string input, we now have this: `registerFileUrl`. In case of existing data (=string input; no file url), I build a data url on the fly. Do you see a problem with this approach or should we add an alternative here directly. WDYT?

**Comment by CGNonofr** [comment]
I think the data url is fine. It's the only things that is guarantee to work everywhere (css files, fetch, fonts...)

blob urls can probably be used instead (but be careful, sometime vscode applies transformation on urls and blob url are not exactly regular urls)

do you see any downside of using data url?

**Comment by CGNonofr** [comment]
I guess we can provide a way to provide a file content instead of its url and create the data-url ourselfves, but I don't really want to encourage that usage either.

**Comment by kaisalmen** [comment]
I will support this in the wrapper, because I support both ways before, but let's leave it out here.
