### ISSUE TITLE
Uncaught Error: Cannot have two contributions with the same id editor.contrib.referencesController

### ISSUE THREAD

**Issue by Seventysevendays** [CodinGame/monaco-vscode-api#162]
initialize got error, what's the problem
![image](https://github.com/CodinGame/monaco-vscode-api/assets/37206679/4354d65f-b294-40cd-8b59-c993e8b5cd4b)

**Comment by CGNonofr** [comment]
This library pulls back vscode features into monaco editor

monaco-editor is trying to do the same with standalone versions of the features, and it conflicts

The solution is to never import `monaco-editor` but `monaco-editor/esm/vs/editor/editor.api.js` instead (you can use your bundler alias feature to do it)

for more details, [these files](https://github.com/microsoft/vscode/blob/b7ebbb6990b1d2a04b5cbbd816cfa73f96b1c1d8/src/vs/editor/editor.main.ts#L8-L14) are specific to the standalone editor (monaco) while there is a vscode version of it (pulled here)

you should probably keep the other imports though ( `monaco-editor/esm/vs/editor/editor.all.js` to keep editor-related features and `vs/editor/standalone/browser/iPadShowKeyboard/iPadShowKeyboard` which is only used in monaco)

**Comment by Seventysevendays** [comment]
> This library pulls back vscode features into monaco editor
> 
> monaco-editor is trying to do the same with standalone versions of the features, and it conflicts
> 
> The solution is to never import `monaco-editor` but `monaco-editor/esm/vs/editor/editor.api.js` instead (you can use your bundler alias feature to do it)
> 
> for more details, [these files](https://github.com/microsoft/vscode/blob/b7ebbb6990b1d2a04b5cbbd816cfa73f96b1c1d8/src/vs/editor/editor.main.ts#L8-L14) are specific to the standalone editor (monaco) while there is a vscode version of it (pulled here)
> 
> you should probably keep the other imports though ( `monaco-editor/esm/vs/editor/editor.all.js` to keep editor-related features and `vs/editor/standalone/browser/iPadShowKeyboard/iPadShowKeyboard` which is only used in monaco)

it works, thanks so much

**Comment by jhk-mjolner** [comment]
For anyone finding themselves here, wondering if they should import monaco-editor as `monaco-editor/esm/vs/editor/editor.api.js` for whatever reason:

You should not. According to https://github.com/TypeFox/monaco-languageclient/issues/562#issuecomment-1776796703

It can cause bugs to appear, such as causing the message for an editor set to be readonly to not appear.
So if you're still importing as `monaco-editor/esm/vs/editor/editor.api.js` (or using a bundler alias to do so) with the latest version, you should probably change that.
