### ISSUE TITLE
Github Copilot Extension

### ISSUE THREAD

**Issue by dkattan** [CodinGame/monaco-vscode-api#174]
Would it be possible to load the GitHub Copilot extension into the demo project?

I'm trying to get it running locally now to try it out, but it might be a 5 minutes you 5 hours me thing :D

**Comment by CGNonofr** [comment]
I don't know, is it a web compatible extension? Trying would take a long time even for you (:

**Comment by dkattan** [comment]
![image](https://github.com/CodinGame/monaco-vscode-api/assets/1424395/8fa87d72-359d-4ce6-8796-f12ff9d85091)

:-/

**Comment by dkattan** [comment]
However, it appears to be compatible with Github Codespaces 
https://docs.github.com/en/codespaces/codespaces-reference/using-github-copilot-in-github-codespaces

So maybe there's a chance...

**Comment by CGNonofr** [comment]
Since v1.82, you can use the vscode server with that library, allowing to run any vscode extension as soon as you have a server to connect to
