### ISSUE TITLE
Incorrect usage of peer dependencies

### ISSUE THREAD

**Issue by BusinessDuck** [CodinGame/monaco-vscode-api#178]
Packages that are built into an environment that is guaranteed to have external modules use peer dependencies. In your case, only `monaco-editor` is guaranteed, other modules, such as `vscode-textmate`, are not used by external environments with a high degree of probability. Therefore, they should not be in peer dependencies. It obliges to configure the external environment.

If npm installs peer dependencies then it's more of a side effect of npm settings due to [issues with React modules](https://github.com/npm/rfcs/blob/main/implemented/0025-install-peer-deps.md#a-leave-it).

Your project does not belong to the React environment and would like to follow the general standards for using modules. Based on logic:

If the project uses modules in the js bundles code and if the external environment does not guarantee the presence of a module, then it should not be optional. If the external environment guarantees the presence of a module, then it is optional in dependencies.

If you don't want to move modules to `dependencies` section, we can try hack it by `peerDependenciesMeta`, more details [here](https://github.com/npm/rfcs/blob/main/implemented/0025-install-peer-deps.md#a-leave-it)

It works same for pnpm/yarn/npm 

```
{
  "peerDependencies": {
    "foo": "1.x",
    "bar": "2.x"
  },
  "peerDependenciesMeta": {
    "foo": {
      "autoinstall": true
    },
    "bar": {
      "autoinstall": false
    }
  }
}
```

This issue also relates to:
https://github.com/TypeFox/monaco-languageclient/issues/514
https://github.com/TypeFox/monaco-languageclient/issues/530
https://github.com/TypeFox/monaco-languageclient/issues/524

**Comment by BusinessDuck** [comment]
**More examples:**

**Typings usage:** (dev dependency)

```
dist/vscode/vs/workbench/services/textMate/browser/textMateTokenizationFeature.d.ts
```

```
import { IGrammar } from 'vscode-textmate';
```

**JS Usage in dist** (direct dependency)

```
dist/vscode/vs/workbench/services/textMate/browser/backgroundTokenization/worker/textMateTokenizationWorker.worker.js
```

```
import * as vscodeTextmate from 'vscode-textmate';
```

**Comment by CGNonofr** [comment]
You're right, I'm not happy with peerDependencies

The issue here is that some entrypoints require some dependencies. If you use no service-override, you don't need any of the peerDependencies.

I'm really not sure how to handle it. Maybe having them as dependencies is fine. It'll make the final project download them without using them, that's the only issue

Any PR is welcome!

**Comment by BusinessDuck** [comment]
We need to split this package to several.  See example below:
```typescript
import { quickAccessService } from "@vscode/quick-access-service";
import { modelService } from "@vscode/model-service";

// install Monaco language client services, need to run monaco module after monaco-treemending
await monacoLsp.initServices({
	quickAccessService:  quickAccessService({ configure my service here }),
	modelService: modelService({ configure my model service here }),
});
```

As a quick fix i recommend move these modules to 'dependencies'

**Comment by CGNonofr** [comment]
It's complicated to split it in different package since there is a lot of code in common

or maybe, we can just leave all the code in the main package and create meta packages with those dependencies, what do you think?

I'm ok to move everything to dependencies, do you mind open the PR? what do you think @kaisalmen ?

**Comment by BusinessDuck** [comment]
npm workspaces can help you share common code and keep you code base inside monorepository 

Details here: https://docs.npmjs.com/cli/v7/using-npm/workspaces#adding-dependencies-to-a-workspace

**Comment by BusinessDuck** [comment]
I tried to make some PR's but build process didn't work on macos, i tried to fix that, but it still don't work. Contribution guide should helps with that

**Comment by CGNonofr** [comment]
monorepo can help to share code in different project, but by doing so the code will be duplicated in every packages published tarball. We can generate those meta-package on the fly pretty easily I think (just a package.json with proper dependencies, and an entrypoint just importing the proper service override)

> I tried to make some PR's but build process didn't work on macos, i tried to fix that, but it still don't work. Contribution guide should helps with that

Feel free to write some documentation, I don't have any way to test on macos

**Comment by kaisalmen** [comment]
Move everything to dependencies and keep `monaco-editor` with a fairly hard version constraint in peerDependencies plus meta data with `autoinstall=true`.

On the end-user/application side shouldn't treeshaking (bundler) allow you to move out unused code independent of how the original dependency was declared, right?

> I tried to make some PR's but build process didn't work on macos

Use Gitpod: https://gitpod.io/new/#https://github.com/CodinGame/monaco-vscode-api

**Comment by BusinessDuck** [comment]
>On the end-user/application side shouldn't treeshaking (bundler) allow you to move out unused code independent of how the original dependency was declared, right?

Three-shaking do remove unused code with unused dependencies.

**Comment by BusinessDuck** [comment]
>Move everything to dependencies and keep monaco-editor with a fairly hard version constraint in peerDependencies 
I Agree. As i told, monaco-editor is required in external env

**Comment by CGNonofr** [comment]
@BusinessDuck what do you think of https://github.com/CodinGame/monaco-vscode-api/pull/191 ?
