### ISSUE TITLE
Expose vite dev server plugin?

### ISSUE THREAD

**Issue by kaisalmen** [CodinGame/monaco-vscode-api#179]
@CGNonofr Is it possible to expose the vite dev server `import.meta.url` [workaround plugin](https://github.com/CodinGame/monaco-vscode-api/blob/main/demo/vite.config.ts#L63-L88) as another npm sub export of `monaco-vscode-api`?

I have copied an now outdated version and used it at different places. I also just realized that when people used vscode default-extension in a vite dev server they all have the same problems. It is easier to tell them, please use this sub export from `monaco-vscode-api` instead of copying code that gets outdated. WDYT?

**Comment by CGNonofr** [comment]
Either that or a library of its own since it's not really specific to this library! or even opening a PR to integrate it directly in vite? :D what do you think?

**Comment by kaisalmen** [comment]
> or even opening a PR to integrate it directly in vite? :D what do you think?

Yeah, why not. If that takes too long or they don't want it, then plan B.

**Comment by CGNonofr** [comment]
I just had a look at it and [it seems pretty easy](https://github.com/vitejs/vite/blob/65b690657f0f97ef7912f3f45002c725d4bcc989/packages/vite/src/node/config.ts#L722C23-L726)

**Comment by CGNonofr** [comment]
Do you mind doing it?

**Comment by kaisalmen** [comment]
Isn't it easier you do it, because you created it?

**Comment by CGNonofr** [comment]
=> https://github.com/vitejs/vite/pull/14260

**Comment by CGNonofr** [comment]
> @CGNonofr nobody is interested in your PR? ⬆️

:cry:

**Comment by kaisalmen** [comment]
Let's leave this open until there is a clear way forward in the linked issue, ok?

**Comment by CGNonofr** [comment]
Is there another way than posting a new comment every 3 days ?

**Comment by kaisalmen** [comment]
> Is there another way than posting a new comment every 3 days ?

Don't know. 😆 Then let's close this.

**Comment by CGNonofr** [comment]
It seems there is a way to ignore issues with a label, I'll do something

**Comment by kaisalmen** [comment]
@CGNonofr vite 5 did not change anything with this problem, did it? They changed some `import.meta.env` handling, but that is unrelated, I guess.

**Comment by CGNonofr** [comment]
I don't think there is any improvement regarding it :-\

**Comment by kaisalmen** [comment]
@CGNonofr with all the upcoming changes can you just contain this plugin as an extra package / sub-export somewhere, please? 🙏 Don't know when the "vitesters" are going to look at the PR again.

**Comment by CGNonofr** [comment]
> @CGNonofr with all the upcoming changes can you just contain this plugin as an extra package / sub-export somewhere, please? 🙏 Don't know when the "vitesters" are going to look at the PR again.

I'm pretty disappointed by the reaction time of the contributors of the various libraries we use here... will try to do something about it soon
