### ISSUE TITLE
DiagnosticFeature not working after upgrade

### ISSUE THREAD

**Issue by AXeL-dev** [CodinGame/monaco-vscode-api#180]
Hey again,

We recently upgraded the `monaco-languageclient` package from version `4.0.3` to version `6.3.0-next.2`, & since then the LSP `DiagnosticFeature` stopped working.

After spending some time on trying to understand the source of the issue, i noticed that it was due to some vscode api changes, i'll try to explain my conclusions below:

1. The `vscode/dist/api.js` file has considerably changed & more exactly the `tabs` getter which has been moved to a separate file, below the old implementation:

![Screen Capture_select-area_20230831181022](https://github.com/CodinGame/monaco-vscode-api/assets/30635693/4652d1e4-bd46-484f-a925-c6c484753469)

& here is the new one, which is now located at `vscode/dist/vscode/vs/workbench/api/common/extHostEditorTabs.js`:

![Screen Capture_select-area_20230831181642](https://github.com/CodinGame/monaco-vscode-api/assets/30635693/f41866aa-b2d9-4889-ab0e-518b1afc448a)

2. As a result to the above change(s), the `tabs` property is now always empty even when having opened monaco editor tabs:

![Screen Capture_select-area_20230831183447](https://github.com/CodinGame/monaco-vscode-api/assets/30635693/c876957a-27e0-4b7d-a589-a8d6f940bbcf)

3. The diagnostic feature does verify if the current `TextDocument` matches with a visible tab & since the `tabs` list is always empty in our case the check always fails & the diagnostic requests are not sent to the LSP server:

![Screen Capture_select-area_20230831183616](https://github.com/CodinGame/monaco-vscode-api/assets/30635693/d2e6ab6f-6a76-4dee-90cb-41f314f14c23)

I think that providing a way to override the `tabs getter` would fix the issue, still i'm not sure if that's doable on this package side or on the vscode api side, what do you think @kaisalmen ?

**Comment by AXeL-dev** [comment]
**Edit**: I tried to modified the vscode api from the `node_modules` but it still didn't work, i'm unable to get the models:

![Screen Capture_select-area_20230831185922](https://github.com/CodinGame/monaco-vscode-api/assets/30635693/5d6183a0-9ed2-4ccf-8140-f62003105456)

**Comment by AXeL-dev** [comment]
@kaisalmen @CGNonofr Any help on this please?

**Comment by CGNonofr** [comment]
Thanks for the investigation, I will have a look at it!

**Comment by CGNonofr** [comment]
Can you give a try at `@codingame/monaco-vscode-api@1.81.7-next.0`?

**Comment by AXeL-dev** [comment]
The issue is still persisting in `@codingame/monaco-vscode-api@1.81.7-next.0`:

![Screen Capture_select-area_20230901204255](https://github.com/CodinGame/monaco-vscode-api/assets/30635693/2e68f2d6-0ea4-45a0-a3d3-6d6fc632ec73)


![Screen Capture_select-area_20230901204035](https://github.com/CodinGame/monaco-vscode-api/assets/30635693/5613a68b-6a66-4035-bd34-caeb2e3d43ed)

**Comment by CGNonofr** [comment]
I'm... confused ! Are you sure there is no cache issue? Do you use the editor service override or the views?

**Comment by AXeL-dev** [comment]
I completely deleted the `node_modules` folder & the` package-lock.json` file & reinstalled all the dependencies.

Yes, i'm using the `codeEditorService` override to register a custom open handler:

![Screen Capture_select-area_20230901205222](https://github.com/CodinGame/monaco-vscode-api/assets/30635693/76076018-9447-4567-b912-7f2201791f4b)

Also, i'm using `react` & `@monaco-editor/react` to create my editors.

**Comment by CGNonofr** [comment]
Ok. For it to work you need to use either the editor service override or the views service override

**Comment by AXeL-dev** [comment]
@CGNonofr I'm not sure if i get you well, do i need to override a specific function of the editor service? maybe the `getEditors` callback?

![Screen Capture_select-area_20230901210119](https://github.com/CodinGame/monaco-vscode-api/assets/30635693/8dcbd8be-4981-47ee-ac46-0d352fea7557)

![Screen Capture_select-area_20230901210138](https://github.com/CodinGame/monaco-vscode-api/assets/30635693/e0ecbbf5-bf56-4f8e-a236-68787964cbf8)

**Comment by CGNonofr** [comment]
I'm not sure to understand your screenshots either

What does that mean to override by something from StandaloneServices which mean the services are already initialized?

I was talking about using `vscode/service-override/editor` or `vscode/service-override/views`

**Comment by AXeL-dev** [comment]
@CGNonofr Nevermind, i think that i get you now, actually i just needed to add the following config:

![Screen Capture_select-area_20230901211106](https://github.com/CodinGame/monaco-vscode-api/assets/30635693/816080f4-d3b4-4e4b-93d7-d22bc8a4d511)

The diagnostics works now! Thanks a lot & sorry for the confusion :pray: .

**Comment by CGNonofr** [comment]
You probably shouldn't use the view service except if you need it as it pulls a lot of code, but the editor service instead

**Comment by AXeL-dev** [comment]
Alright, thanks again of the fix!

**Comment by kaisalmen** [comment]
@AXeL-dev I need to release a new version of `monaco-languageclient` (probably `6.4.6`) that contains the latest version (1.81.7 once it is available).
