### ISSUE TITLE
Failing to load vscode-oniguruma wasm (and other files) since 1.80

### ISSUE THREAD

**Issue by jhk-mjolner** [CodinGame/monaco-vscode-api#186]
I've tried upgrading from monaco-languageclient 6.0.3 to the latest 6.4.6, and got several errors in the browser console related to not being allowed to load local resources.
I've tried different versions, and concluded that the error first appears in version 6.3.0 which uses 1.80 of monaco-vscode-api.

Error examples from browser console:
`Not allowed to load local resource: file:///C:/<PATH_TO_MY_PROJECT>/node_modules/vscode/dist/service-override/vscode-oniguruma/release/onig.wasm`
`Not allowed to load local resource: file:///C:/<PATH_TO_MY_PROJECT>/frontend/node_modules/vscode/dist/default-extensions/theme-defaults/light_modern.json` (there's several of this kind of error, about trying to load various theme .json files)
And those files rightly aren't there, so webpack can't bundle them and serve them as resources.
The error is thrown from `node_modules\vscode\dist\vscode\vs\workbench\services\textMate\browser\textMateTokenizationFeatureImpl.js` in `async _loadVSCodeOnigurumaWASM()` where it tries to load the path `'vscode-oniguruma/../onig.wasm'`

I've tried looking at some source code and believe this change might be the culprit: https://github.com/CodinGame/monaco-vscode-api/commit/e641ac323eb8e29c9496ab87eae345823a090333 as it was introduced in 1.80, remains in 1.81.7 (latest), and changes how the path to the wasm file is resolved.
Perhaps another similar change in another commit, also introduced in 1.80, might explain the same error for the theme .json file(s)?

I'm using Angular and an `extra-webpack.config.js` file to add webpack configuration and have this part for loading wasm, that worked fine before version 1.80:
```js
      {
        test: /\.(mp3|wasm|ttf)$/i,
        type: 'asset/resource',
      },
      {
        test: /\.wasm$/,
        type: 'asset/inline',
      },
```

Is there some configuration I can use, either for monaco-languageclient, monaco-vscode-api or webpack, that can resolve this issue?
Or does it require code changes from your side?

**Comment by CGNonofr** [comment]
I see you are on windows and I've never tested it on that platform, maybe the `C:/` part breaks it? (at least for the extension files part: `light_modern.json` for instance`)

Regarding the wasm loading issue, did you try to add an alias from `vscode-oniguruma/release/onig.wasm` to the absolute file path in the webpack config?

**Comment by jhk-mjolner** [comment]
I don't expect the C:/ part to be a problem, I think the problem is that the wasm is located at
`C:\<PATH_TO_MY_PROEJCT>\node_modules\vscode-oniguruma\release\onig.wasm` not `C:/<PATH_TO_MY_PROJECT>/node_modules/vscode/dist/service-override/vscode-oniguruma/release/onig.wasm`. It's the parent path relative within node_modules that has changed, I believe.

Regarding the webpack alias, I'm not sure I'm using the feature correctly, but none of these additions helped:
```js
    alias: {
      // 'vscode-oniguruma/../onig.wasm': resolve(__dirname, './node_modules/vscode-oniguruma/release/onig.wasm'),
      // 'vscode-oniguruma/release/onig.wasm': resolve(__dirname, './node_modules/vscode-oniguruma/release/onig.wasm'),
      // 'vscode-oniguruma/../onig.wasm': './node_modules/vscode-oniguruma/release/onig.wasm',
      // 'vscode-oniguruma/release/onig.wasm': './node_modules/vscode-oniguruma/release/onig.wasm',
      // 'vscode-oniguruma/../onig.wasm': 'C:\\<PATH_TO_MY_PROJECT>\\node_modules\\vscode-oniguruma\\release\\onig.wasm',
      // 'vscode-oniguruma/release/onig.wasm': 'C:\\<PATH_TO_MY_PROJECT>\\node_modules\\vscode-oniguruma\\release\\onig.wasm',
      // 'C:\\<PATH_TO_MY_PROJECT>\\node_modules\\vscode-oniguruma\\release\\onig.wasm': 'vscode-oniguruma/../onig.wasm',
      // 'C:\\<PATH_TO_MY_PROJECT>\\node_modules\\vscode-oniguruma\\release\\onig.wasm': 'vscode-oniguruma/release/onig.wasm',
    },
```

**Comment by CGNonofr** [comment]
It seems that webpack fails to resolve `vscode-oniguruma\release\onig.wasm` and consider it as a relative path

I'm not sure how the `new URL(..., import.meta.url)` syntax is handled in webpack, that's the only absolute import using this syntax in the code

**Comment by jhk-mjolner** [comment]
Yeah, it seems like that's the issue.
I'm guessing the change can't be rolled back as it fixed something else?
I've tried looking at how webpack handles `new URL()`, but I'm not finding anything relevant for this case.

I don't know how much experience you have with webpack, but do you have any other ideas I could try?

**Comment by jhk-mjolner** [comment]
> isn't is related to https://stackoverflow.com/questions/74038161/angular-cli-and-loading-assets-with-import-meta-url-causing-not-allowed-to-load ?

Yes! 

Adding 
```js
module.exports = {
  module: {
    parser: {
      javascript: {
        url: true,
      },
    },
  },
};
```
and deleting the .angular folder as suggested in https://stackoverflow.com/a/75252098 seems to have resolved the issue for me.

**Comment by CGNonofr** [comment]
both issues?

**Comment by jhk-mjolner** [comment]
Yes, also the .json file loading issue. Thanks!

In the issue linked in the answer you linked, they also suggest migrating to esbuild which Angular experimentally supports now. Do you know whether using esbuild is more or less supported by monaco-languageclient and monaco-vscode-api?

**Comment by jhk-mjolner** [comment]
Taking another look at https://github.com/TypeFox/monaco-languageclient-ng-example/blob/main/custom-webpack.config.js I can also see it already includes these lines, but only mentions a 'ttf url loading issue' which I haven't had, so I haven't used those lines.
I'll suggest to them that they add that it's now necessary to load the wasm too.

**Comment by CGNonofr** [comment]
I'm not sure. esbuild is used by vite in the demo of this project, we need a small hack to make it work in dev mode: https://github.com/CodinGame/monaco-vscode-api/blob/40ba45c5816c2e98dbb577dc51a83e1d6123a37f/demo/vite.config.ts#L62-L90

**Comment by jhk-mjolner** [comment]
I can also see that the change to new URL() syntax and the related issues are mentioned in the readme for this repo https://github.com/CodinGame/monaco-vscode-api#troubleshooting 
Maybe it could be worth mentioning the issues webpack has with the syntax and how to fix it. Maybe link https://github.com/TypeFox/monaco-languageclient-ng-example/blob/main/custom-webpack.config.js as well.

**Comment by CGNonofr** [comment]
Is it related to webpack of to the angular cli though?

**Comment by jhk-mjolner** [comment]
Ah, right, it was mostly an Angular specific thing, and if you don't want to include troubleshooting for specific web component frameworks, I guess it shouldn't be added.

**Comment by CGNonofr** [comment]
It can still be added in a troubleshooting section, feel free to open an MR ;)

**Comment by jhk-mjolner** [comment]
I thought about what would make sense to write. I could write something only about using Angular and Webpack, but I guess more than `parser.javascript.url: true` is needed from the monaco-languageclient-ng-example webpack configuration. I just don't know how much.

In general, I could boil the guidance down to "look at the examples from monaco-languageclient". But I'm not sure how much of the configuration in those examples is needed for this project alone, or even how many people will be using this project without monaco-languageclient. And maybe being dependent on another project/repo for guidance is less than ideal?

**Comment by CGNonofr** [comment]
I guess it can be very pragmatic: if you encounter this specific error, here's something you can try (maybe with some hints on the reasons that can cause this: angular-cli)

**Comment by fumeboy** [comment]
i meet something wrong with the same file `onig.wasm`, I publish my vite project which using @codingame/services as a browser library, and have an example page to import my published lib, and i have the problem below:

![image](https://github.com/CodinGame/monaco-vscode-api/assets/30453942/45066fc5-26ea-4218-ad78-cfd55e50fa7f)

**Comment by CGNonofr** [comment]
There is something wrong with your vite configuration, the library just includes a `new URL('[...]/onig.wasm', import.meta.url)`. If it doesn't work, it's a matter of bundlers
