### ISSUE TITLE
Ability to pass a container to the `initialize` method

### ISSUE THREAD

**Issue by VVeaz** [CodinGame/monaco-vscode-api#190]
I use `initServices` method from package `monaco-language-client`

`initServices` calls `importAllServices` (also `monaco-language-client`)

`importAllServices`  calls `initialize` (named as `initializeMonacoService` ) from this package - `@codingame/monaco-vscode-api`
(dist\services.js)

`initialize` calls `initServices` (also `@codingame/monaco-vscode-api`)

 `initServices` calls `getServiceOverride` (also `@codingame/monaco-vscode-api`) without argument.
 
 `getServiceOverride` has optional argument - `container` and I want to use it. I think that the container containing monaco-editor should be passed there. Otherwise, color "leaks" occur because the `monaco-workbench` css class is assigned to the body, e.g. the scrollbar in Firefox changes color when the editor's theme changes.
 
 Realted issue: https://github.com/TypeFox/monaco-languageclient/issues/537

**Comment by CGNonofr** [comment]
This library already allows to provide a different container, if a change needs to be done, it's on monaco-languageclient

**Comment by VVeaz** [comment]
Thanks for the quick reply. Of course, you're right, the `getServiceOverride` method can accept a different container. But I believe that its indirect use in the `initialize` -> `initServices` methods (now I'm talking about `initServices` from this library) should also be possible with the container argument. E.g. like this:
![image](https://github.com/CodinGame/monaco-vscode-api/assets/36280384/337b4ecc-34a9-497f-a458-db5ee1711803)

![image](https://github.com/CodinGame/monaco-vscode-api/assets/36280384/cc6e9600-ef80-41e3-8599-9b2243a9383c)
