### ISSUE TITLE
Ability to use colorizeElements

### ISSUE THREAD

**Issue by kevinvalk** [CodinGame/monaco-vscode-api#192]
Monaco has this awesome method to colorize elements https://microsoft.github.io/monaco-editor/docs.html#functions/editor.colorizeElement.html. This is great for website if you are already bundling Monaco so you do not need to rely on prism or any other syntax highlighting libraries. As far as I can see, using monaco.editor.colorizeElement will not use any of the installed extensions, themes, etc provided through the initialize method from monaco-vscode-api.

Is it possible to use colorizeElements https://github.com/microsoft/vscode/blob/main/src/vs/editor/standalone/browser/colorizer.ts that will also include any language extensions etc provided via `initialize`?

**Comment by CGNonofr** [comment]
I'm surprised it doesn't work, the last time I tried it was ok.

I'll try to have a look at it

**Comment by CGNonofr** [comment]
I've just tried and everything seems to work just fine

Be careful about `colorizeElement`, for some reasons it overrides the theme, no matter what, even if you don't provide the option. Maybe should use the `colorize` function instead.

Do you wait for the language extension to be loaded before trying to run the coloration?

Btw, a better option for you is probably to render an editor, and customize it to remove everything you don't need (line numbers, gutter, folding... ?), make it readonly and set it's height to the same value as its content height

**Comment by kevinvalk** [comment]
Thanks for the input, yep totally works (with the quirks mentioned above)!
