### ISSUE TITLE
Uninitialize or fully disable command palette and other global keybindings

### ISSUE THREAD

**Issue by kevinvalk** [CodinGame/monaco-vscode-api#193]
Maybe I am completely missing something, but how do we correctly "uninitialize" vscode? This could be useful if you have a bigger website that only uses vscode/monaco in a specific area of the website. If you then browse away from this section it would be nice to properly unload vscode (think also performance/battery drain on laptops etc).

An alternative would be to fully disable quickaccess (command palette) without causing console warning (and possible any other keybindings???).
```typescript
await initialize({
        ...
        ...getQuickAccessServiceOverride({
          isKeybindingConfigurationVisible: () => false,
          shouldUseGlobalPicker: () => false, // <--- Illustrated for this issue, this will cause the warning if you have no editor instance in focus.
        }),
        ...
});
``` 
<img width="638" alt="image" src="https://github.com/CodinGame/monaco-vscode-api/assets/3524694/77d3e55f-fb0f-479a-8c09-27e9228e4648">

**Comment by CGNonofr** [comment]
Unfortunately, since everything comes from vscode, nothing was designed to be "unloadable". The only reliable way to unload it is to... reload the page.

I don't think it really drains the battery, at most it consumes memory.

We can do something to remove that error though

**Comment by CGNonofr** [comment]
https://github.com/CodinGame/monaco-vscode-api/pull/195 will add a parameter to disable the global keybinding handling

**Comment by kevinvalk** [comment]
Awesome, thanks a lot for these changes! Nice work!

Small detail that you may want to add. If you have an editor in focus, the "local" quick access/command palette is used (i.e. it is rendered to the top of the editor instance) regardless of `shouldUseGlobalPicker`. In my opinion when you are using `shouldUseGlobalPicker: () => true` in the quick access service it should ALWAYS show the "global" quick access (i.e. it is rendered outside the editor instance) even when an editor is in focus.

Combined with the new `shouldUseGlobalKeybindings` method you can make some nice UX I think!

**Comment by CGNonofr** [comment]
> Small detail that you may want to add. If you have an editor in focus, the "local" quick access/command palette is used (i.e. it is rendered to the top of the editor instance) regardless of `shouldUseGlobalPicker`. In my opinion when you are using `shouldUseGlobalPicker: () => true` in the quick access service it should ALWAYS show the "global" quick access (i.e. it is rendered outside the editor instance) even when an editor is in focus.

You're completely right!
