### ISSUE TITLE
Disable workspace trust or override configuration service

### ISSUE THREAD

**Issue by kevinvalk** [CodinGame/monaco-vscode-api#196]
By default all workspaces are trusted when using monaco-vscode-api.
https://github.com/CodinGame/monaco-vscode-api/blob/76ba9377379225341ace31b97d1b7f4d9a9e3319/src/missing-services.ts#L691

This means that when you use `workspace.updateWorkspaceFolder` VSCode will start searching for `.vscode/settings.json` etc in your workspace folder and if it exist apply those settings.
https://github.com/microsoft/vscode/blob/15cdbeec2067d006517b946bf17edfd54abf4adb/src/vs/workbench/services/configuration/browser/configurationService.ts#L945-L951

In my case the workspace folder is actually not trusted and I do not want to load (and apply) these settings. I think the easiest and logical option should be a way to set workspace trust (maybe even default it to false?) https://github.com/microsoft/vscode/blob/15cdbeec2067d006517b946bf17edfd54abf4adb/src/vs/workbench/services/configuration/browser/configuration.ts#L680-

Errors in the console you will get from VSCode IFF the .vscode settings file do not exist:
```
  ERR Error: Unable to read file 'some-scheme:/styling-webpack/.vscode/launch.json' (Error: Unable to read file 'some-scheme:/styling-webpack/.vscode/launch.json' that is actually a directory)
    at MemoryFileService2.restoreReadError (fileService.js:406:18)
    at MemoryFileService2.doReadFileStream (fileService.js:390:24)
    at async MemoryFileService2.doReadFile (fileService.js:344:24)
    at async configuration.js:205:41
    at async Promise.all (:8000/kevinvalk/storybook/code/designs/CHANGELOG.md/index 1)
    at async Promise.all (:8000/kevinvalk/storybook/code/designs/CHANGELOG.md/index 1)
    at async FileServiceBasedConfiguration.resolveContents (configuration.js:218:70)
    at async FileServiceBasedConfiguration.loadConfiguration (configuration.js:227:68)
    at async Promise.all (:8000/kevinvalk/storybook/code/designs/CHANGELOG.md/index 1)
    at async InjectedConfigurationService2.onFoldersChanged (configurationService.js:819:42)
```

**Comment by CGNonofr** [comment]
Indeed, workspace trust management is mocked in this library for the moment.

You are free to provide you own implementation of the `IWorkspaceTrustRequestService` though returning false to `requestWorkspaceTrust`

**Comment by kevinvalk** [comment]
I think I may be missing something, but `IWorkspaceTrustRequestService` is not exported right?

**Comment by kevinvalk** [comment]
You work super fast, sick!

P.S. I have noticed this a few more times  were I would have liked to override a service. As far as I can see, you can not "just" use the original vscode exports and everything needs to be exposed via monaco-vscode-api. Could there a more generic approach to exposes ALL services (without guarantees nor demo code)? This way it saves you a bunch of time and this API becomes quite a bit more flexible?

**Comment by kevinvalk** [comment]
Version 1.82.3 implements this, however I still see file requests for `.vscode/settings.json` etc. Moreover, I cannot get this to work.
```json
{
"workbench.colorTheme": "some different theme",
}
```

```typescript
    ...getEnvironmentServiceOverride({
      enableWorkspaceTrust: true,
    }),
    ...getWorkspaceTrustOverride(),
```

Nor if I provide a custom class
```typescript
class WorkspaceTrustEnablementService implements IWorkspaceTrustEnablementService {
  _serviceBrand: undefined;
  isWorkspaceTrustEnabled(): boolean {
    return true;
  }
}

...

    [IWorkspaceTrustEnablementService.toString()]: new SyncDescriptor(
      WorkspaceTrustEnablementService,
      undefined,
      false
    ),
```

Regardless of all this, I get file reads and I even see the workbench.colorTheme being applied (for both true and false trust)
```
DEBUG Configuration keys changed in WORKSPACE_FOLDER target workbench.colorTheme
```

P.S. The theme does not change, not sure if and how this is related.

**Comment by CGNonofr** [comment]
When enabling the workspace trust service, it'll ask the user if they trust the workspace using the dialogService then stores the result in the storageService. In the meantime, I don't really know the state of the workspace...

I don't know if there is a way to never trust workspace without asking the user (except maybe intercepting the dialogService call to return to not trust the workspace?)

**Comment by kevinvalk** [comment]
Aaa I see, will do some more debugging and playing around to figure out what VSCode really wants here to see if we can set it programatically. Will report back with info, thanks for yours ;)
