### ISSUE TITLE
Cannot use spaces in filename

### ISSUE THREAD

**Issue by mehulmpt** [CodinGame/monaco-vscode-api#198]
There is a bug with how inputs in file explorer are handled. For example, on the demo page (https://codingame.github.io/monaco-vscode-api/) try to create a new file with name `hello world.txt`. You won't be able to because space doesn't work as expected. Furthermore `Cmd + A` to select all selects the folder group instead of the text inside input.

## Bug reproduction

https://github.com/CodinGame/monaco-vscode-api/assets/10388889/5a827f0e-4b54-45b0-8f35-480b2cd46143

## Actual VS code behavior

https://github.com/CodinGame/monaco-vscode-api/assets/10388889/a8adf8b4-872b-47a8-84e0-e1762ba772e5

**Comment by CGNonofr** [comment]
Thanks for the report, nicely done!

It looks like a difficult bug to debug though :cry:
