### ISSUE TITLE
main package now requires skipLibCheck=true

### ISSUE THREAD

**Issue by kaisalmen** [CodinGame/monaco-vscode-api#201]
Hi @CGNonofr 

because the main because is now only dependent on `monaco-editor` the typescript compilation now only succeeds with `skipLibCheck=true`.

I have reproduced this on two branches with the Angular example repo:

With lib checking enabled:
https://github.com/TypeFox/monaco-languageclient-ng-example/actions/runs/6422702376/job/17439750585

With lib checking disabled:
https://github.com/TypeFox/monaco-languageclient-ng-example/actions/runs/6422712538/job/17439771153

It is the same behaviour with `monaco-languageclient`. With the latest commit on `main` I globally enabled lib checking, but disabled it where it is required (packages client, examples and verify/webpack).

The problematic code/definitions are terminal related things and xterm related dependencies. Do you have a good idea how to fix this?

**Comment by kaisalmen** [comment]
Sorry, corrected the title. Why isn't it called `enableLibCheck`? 😅

**Comment by CGNonofr** [comment]
I'm surprised, typescript also checks code that is not used at all?

**Comment by kaisalmen** [comment]
> I'm surprised, typescript also checks code that is not used at all?

It must end up in the code-graph somehow. There must be some erroneous import or so somewhere, because otherwise this problem would not be constraint to the terminal.

**Comment by CGNonofr** [comment]
> > I'm surprised, typescript also checks code that is not used at all?
> 
> It must end up in the code-graph somehow. There must be some erroneous import or so somewhere, because otherwise this problem would not be constraint to the terminal.

indeed: `services.d.ts` => `vscode/src/vs/workbench/contrib/terminal/browser/terminal.d.ts` => `vscode/src/vs/platform/terminal/common/capabilities/capabilities.d.ts` => `vscode/src/vs/platform/terminal/common/capabilities/commandDetectionCapability.d.ts` => `xterm-headless`

Not sure how to handle it!

One way is to stop exporting all services identifiers from there but it will be a breaking change
