### ISSUE TITLE
initialize services error with vscode-textmate

### ISSUE THREAD

**Issue by KamiC6238** [CodinGame/monaco-vscode-api#204]
I want to use this library to do something, and tried to initialze services like the follow image:
<img width="1259" alt="image" src="https://github.com/CodinGame/monaco-vscode-api/assets/23523595/9cb65259-bab1-49ca-bd55-b88699042ed5">

And then I got some error like that:
<img width="893" alt="image" src="https://github.com/CodinGame/monaco-vscode-api/assets/23523595/9cfead5a-1c54-43c4-9776-e75ebdf7ea63">

Any my pakcage.json:
```json
"devDependencies": {
    "vite": "^4.4.5",
    "vscode": "npm:@codingame/monaco-vscode-api@^1.82.4",
    "vscode-oniguruma": "^2.0.1",
    "vscode-textmate": "^9.0.0"
}
```

Is there something wrong with the way I'm using it? If so, how should I correct this issue? Thank you very much.

**Comment by CGNonofr** [comment]
Is vscode-textmate installed?

With the last version of the lib, you should install and use `@codingame/monaco-vscode-textmate-service-override`

**Comment by KamiC6238** [comment]
> Is vscode-textmate installed?
> 
> With the last version of the lib, you should install and use `@codingame/monaco-vscode-textmate-service-override`

Yes, `vscode-textmate` is already installed, and I replace the `vscode/service-override/textmate` to `@codingame/monaco-vscode-textmate-service-override`, but the error is still exist.

**Comment by CGNonofr** [comment]
vscode-textmate package is built as commonJs for some reasons

Vite is supposed to be able to handle it using the rollup commonjs plugin, I have no idea why it doesn't! There is no issue with the demo here.

It seems more like a vite issue

**Comment by CGNonofr** [comment]
Oh, didn't notice you excluded vscode-textmate from being optimized! why? it's probably your issue

**Comment by KamiC6238** [comment]
> vscode-textmate package is built as commonJs for some reasons
> 
> Vite is supposed to be able to handle it using the rollup commonjs plugin, I have no idea why it doesn't! There is no issue with the demo here.
> 
> It seems more like a vite issue

Thanks for you reply, I will try to using the rollup commonjs plugin

**Comment by CGNonofr** [comment]
(you should check my last answer)

**Comment by KamiC6238** [comment]
> Oh, didn't notice you excluded vscode-textmate from being optimized! why? it's probably your issue
I also remove the `vscode-textmate` from `excluded`, but it not fix the error.

**Comment by CGNonofr** [comment]
You should probably not exclude anything though. Since it's used transitively, not excluding `vscode-textmate` is maybe not enough

**Comment by KamiC6238** [comment]
> You should probably not exclude anything though. Since it's used transitively, not excluding `vscode-textmate` is maybe not enough

It works when I remove the optimizeDeps. 

The reason I put `vscode` in `exclude` is because I saw it done that way in the [demo](https://github.com/CodinGame/monaco-vscode-api/blob/main/demo/vite.config.ts) but I didn't realize I had mistaken `include` for `exclude.`

Thank you very much for your help.
