### ISSUE TITLE
Can I register extension redhat.java and vscode-lombok with this??

### ISSUE THREAD

**Issue by adj5672** [CodinGame/monaco-vscode-api#211]
I'm using monaco-vscode-api and monaco-languageclient to edit Java code with monaco editor.
(with @codingame default java extension)

I have my own language server based on eclipse.jdt.ls and pretty works well like this.

<img width="802" alt="image" src="https://github.com/CodinGame/monaco-vscode-api/assets/77478791/77cf69fe-57ec-4f9a-abbe-2a345adde0f2">

but, there's something I want to register extensions.

It's vscode-lombok..

since my language server has lombok dependency, so annotations of lombok can auto complete.
but, getter and setter method can not be recognized..

<img width="548" alt="image" src="https://github.com/CodinGame/monaco-vscode-api/assets/77478791/33a0ef89-2137-4a3b-a88b-79d1689d37d1">

<img width="429" alt="image" src="https://github.com/CodinGame/monaco-vscode-api/assets/77478791/d697f25c-9f93-4c23-b0a1-b09826a8c21b">

I think that if I register vscode-lombok extension then it may works well..
(since lombok extension use [redhat java extension](https://github.com/redhat-developer/vscode-java), java extension have to register too..)
I don't know how to register extension using registerExtension method..

Is it possible..?? and if possible, how I register that extension... 🥲

**Comment by CGNonofr** [comment]
Yes it's possible, but you'll need the remote ext host server

On the server:
- `npm install -g @codingame/monaco-vscode-server`
- run `vscode-ext-host-server`
- download and extract your extension somewhere

On the client:
- add remoteAgent service override
- provide the `remoteAuthority` of the server to the environment service override as parameter
- register your extension as remote:
```typescript
  registerExtension(extensionManifest, ExtensionHostKind.Remote, {
    path: <path on the extension on the server>
  })
```
extensionManifest is the content of the packageJson of the extension, and the extension path should point to the extension subdirectory containing the package.json

**Comment by adj5672** [comment]
@CGNonofr thanks for your answer :)

I have some additional questions.

1. My understanding is that I need 3 servers. 
client server, language server and remote extension host server.  is it correct?

2. my client server's host is http://localhost:3000 and language server is ws://localhost:30000/java.

when I run vscode-ext-host-server, it seems open with localhost:8000.

<img width="341" alt="image" src="https://github.com/CodinGame/monaco-vscode-api/assets/77478791/1fc6ffde-072e-4f46-b9b0-f595f96e80f7">

then, Is remoteAuthority localhost:8000??

3.  In my code, I set userServices like this. 
and I cannot understand how I provide remoteAuthority to the environment service override as parameter... 🥲

<img width="832" alt="image" src="https://github.com/CodinGame/monaco-vscode-api/assets/77478791/dd2bbfd1-cb89-412b-9022-bc8f0adb183b">

<img width="555" alt="image" src="https://github.com/CodinGame/monaco-vscode-api/assets/77478791/ebf76546-4658-4602-8353-57c8941a8952">

4. Is there any remote ext host example that I can refer to??

**Comment by CGNonofr** [comment]
What is the "client" server ? The vscode extension already includes the language client/server, you don't need anything else

You need the environment service override to set the remoteAuthority

The demo here demonstates it on a simple remote extension

**Comment by adj5672** [comment]
What I meant by client server was langauge client.. 😅

I registered service override like this and extension host looks like works. :) thanks.

<img width="574" alt="image" src="https://github.com/CodinGame/monaco-vscode-api/assets/77478791/98354176-d796-412d-8bb8-703f6b833c4c">

<img width="488" alt="image" src="https://github.com/CodinGame/monaco-vscode-api/assets/77478791/77213f84-365e-4e94-8c6e-3372c73b0b47">

The following warning log also occurred. Is there any problem?

<img width="489" alt="image" src="https://github.com/CodinGame/monaco-vscode-api/assets/77478791/3689a29a-bacf-4e7e-9816-a7b41f663ce7">

Red Hat Java extension seems to have been applied well..
But lombok doesn't seem to apply. 🥲

**Comment by adj5672** [comment]
In my language servers, after set vmargs javaagent lombok path, it perfectly works!!

-javaagent:<path-to-lombok-jar> 
-Xbootclasspath/a:<path-to-lombok-jar>

<img width="679" alt="image" src="https://github.com/CodinGame/monaco-vscode-api/assets/77478791/4a413d36-030c-4b7c-9105-9f3431861641">

<img width="367" alt="image" src="https://github.com/CodinGame/monaco-vscode-api/assets/77478791/5252300b-36b7-4642-aa5b-25b6118f2e6c">

Thanks :)
