### ISSUE TITLE
Unable to resolve nonexistent file

### ISSUE THREAD

**Issue by OliverwengFiltered** [CodinGame/monaco-vscode-api#214]
@CGNonofr ,

it seems with latest version, I started to have this problem. (please see below description)

1. use monaco-vscode-api 1.82.5, monaco editor v0.43.0, and then initialize the editor with javascript or typescript language.
2. go to the web page that has the editor in it, and then type `var foo = "foo"; console.log(foo);`
3. and then hold key "Command" in Mac or "Ctrl" in Windows, and mouse hover over foo, it will produce the error `Unable to resolve nonexistent file`

the error doesn't impact the monaco editor service usage though, but wondering if you have any insights on how to suppress that?

Thank you a lot.

<img width="513" alt="Screenshot 2023-10-16 at 1 35 56 PM" src="https://github.com/CodinGame/monaco-vscode-api/assets/28814939/477e78b2-3e19-421a-a509-30b2d4d1657a">

**Comment by CGNonofr** [comment]
Are you using the typescript-language-features extension? Can you try with the last version? Are you able to reproduce in the demo?

**Comment by OliverwengFiltered** [comment]
tested, can't be reproduced in latest version. closing this now. thanks.

**Comment by OliverwengFiltered** [comment]
@CGNonofr 
sorry for the confusion, it seems in the latest version I can still reproduce it.
recorded a short video for reference.
also providing a public repo for you to reproduce. https://github.com/OliverwengFiltered/monaco-test 


https://github.com/CodinGame/monaco-vscode-api/assets/28814939/3087e605-d19d-4950-8ecc-03623cc36e44

**Comment by CGNonofr** [comment]
It's very difficult to navigate your repo as is contains the node_modules and the dist files.

I didn't find how you enabled the typescript intellisense and what you're using for it

**Comment by OliverwengFiltered** [comment]
removed dists and added readme here: https://github.com/OliverwengFiltered/monaco-test

and in terms of typescript/javascript intellisense, It was default enabled by monaco editor I believe.

**Comment by CGNonofr** [comment]
Instead of using the monaco typescript intellisense, I suggest you use the typescript-language-features vscode extension instead by importing `@codingame/monaco-vscode-typescript-language-features-default-extension`
