### ISSUE TITLE
Error using with monaco-editor-webpack-plugin

### ISSUE THREAD

**Issue by danimasa** [CodinGame/monaco-vscode-api#219]
Hi, I'm having a problem with the _monaco-editor-webpack-plugin_ after running the _treemending_ code:

```
An unhandled rejection has occurred inside Forge:
Error: Cannot find module 'vs/editor/standalone/browser/quickAccess/standaloneGotoLineQuickAccess'
Require stack:
- [...]\node_modules\monaco-editor-webpack-plugin\out\index.js
```

Is there a way to resolve that or some specific webpack configurations?

**Comment by asimaranov** [comment]
Same

**Comment by CGNonofr** [comment]
The monaco-editor metadata are wrong with the treemended version and the webpack plugin relies on it.

You can add this configuration to the plugin:
```typescript
            new MonacoWebpackPlugin({
                features: ['!gotoLine', '!inspectTokens', '!quickCommand', '!quickHelp', '!quickOutline', '!referenceSearch', '!toggleHighContrast']
            })
```

(those features are replaced by their vscode versions)

**Comment by danimasa** [comment]
It worked, thanks!

**Comment by danimasa** [comment]
It worked, thanks!
