### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by aiselp** [CodinGame/monaco-vscode-api#222]
When I updated to version 1.83.5 I found that many imports were no longer available，
After checking the documentation, changing to the following method does not work either.
```js
import getEditorServiceOverride from '@codingame/monaco-vscode-editor-service-override'
import getConfigurationServiceOverride, { updateUserConfiguration, configurationRegistry } from '@codingame/monaco-vscode-configuration-service-override'
```

**Comment by CGNonofr** [comment]
They are separate packages now, you need to install them

**Comment by aiselp** [comment]
Thanks for the answer, but it’s too bad that so many packages have to be installed manually. I suggest you reduce the number of packages.

**Comment by aiselp** [comment]
There are 100+ software packages used in the demo. If you want to install these packages, you must run 100+ installation commands. If you need to update the version in the future, you need to perform this step again, which makes managing dependencies very disadvantageous.

**Comment by CGNonofr** [comment]
The demo tries to demonstrate as much as possible so it requires almost all packages, that's not the case for most of the users

That's the only way to not make user download what they don't need: 1 package = 1 purpose

If you think some of them are likely to be used together, I'm open to create another meta-package that pulls them all

if you want to update them all, you can use [npm-check-updates](https://www.npmjs.com/package/npm-check-updates) => `ncu -i '@codingame/monaco-vscode-*'`

**Comment by aiselp** [comment]
Mainstream packaging tools do not package unused functions together, so I don’t mind downloading more unnecessary content.

**Comment by CGNonofr** [comment]
Well, I do. Some are really heavy. With a meta package, everyone would be happy, right?
