### ISSUE TITLE
createModelReference writefile error

### ISSUE THREAD

**Issue by Seventysevendays** [CodinGame/monaco-vscode-api#223]
![image](https://github.com/CodinGame/monaco-vscode-api/assets/37206679/6dc3001b-121c-477c-ad09-3a8f581091ba)
![image](https://github.com/CodinGame/monaco-vscode-api/assets/37206679/8ad6462b-6b79-49ed-a40c-98d7b4f72804)

on macos its ok, on windows got this error

**Comment by Seventysevendays** [comment]
> Ok, a little bit of context please?

sorry, I added some context

**Comment by CGNonofr** [comment]
Is the problem solved?
