### ISSUE TITLE
BrowserStorageService is not initialized

### ISSUE THREAD

**Issue by CompuIves** [CodinGame/monaco-vscode-api#231]
When we initialize the storage service (using the `StorageService` override), it initialized the `BrowserStorageService` through the `InjectedBrowserStorageService`. However, right now that's not enough to initialize the actual service. To initialize it, we also need to call `initialize()` on the service, like they do here in VSCode code:

```ts
	private async createStorageService(workspace: IAnyWorkspaceIdentifier, logService: ILogService, userDataProfileService: IUserDataProfileService): Promise<IStorageService> {
		const storageService = new BrowserStorageService(workspace, userDataProfileService, logService);

		try {
			await storageService.initialize();

			// Register to close on shutdown
			this.onWillShutdownDisposables.add(toDisposable(() => storageService.close()));

			return storageService;
		} catch (error) {
			onUnexpectedError(error);
			logService.error(error);

			return storageService;
		}
	}
```

Currently we don't do this, and because of this the cache data of e.g. the theme is not cached. I would like to fix this, but I'm not 100% sure how to approach this. The `BrowserStorageService` is initialized in a constructor, which is not async. I wanted to open this issue to discuss approaches.

**Comment by CGNonofr** [comment]
There is a type issue, but it's supposed to be done here => https://github.com/CodinGame/monaco-vscode-api/blob/3b815764fcbd630945c995e49c4e08044217f652/src/service-override/storage.ts#L134

What do you think is the issue with it?

**Comment by CompuIves** [comment]
Very interesting... So from my debugging, it looks like the storage service is accessed already before that participant is executed. The storage service gets called during `initializeMonacoService` by the `WorkbenchThemeService` in its constructor:

<img width="665" alt="image" src="https://github.com/CodinGame/monaco-vscode-api/assets/587016/4a311002-54f6-4d77-baa6-18850f7bc38e">

`WorkbenchThemeService` gets instantiated because of the editor features that are created, looks like SemanticsToken feature needs it:

<img width="645" alt="image" src="https://github.com/CodinGame/monaco-vscode-api/assets/587016/7151a512-aaf8-4d09-9e32-07f686ea91de">

This in turn causes VSCode to default to white theme for a moment. After the constructor of `WorkbenchThemeService` is called, the pre participant is called with the initialisation.

Tricky issue... In VSCode the `BrowserStorageService` is initialised "manually" without dependency injection, and then added to the services. In this case that's a bit harder I reckon.

Maybe we should call all pre participants before we initialize the editor features?

**Comment by CompuIves** [comment]
Ah, I see the challenge... So Monaco is instantiating those editor features, when we call `StandaloneServices.initialize`, and only after that has been done, we call `startup`. 

<img width="584" alt="image" src="https://github.com/CodinGame/monaco-vscode-api/assets/587016/a5f906b6-fe36-4544-90c3-c3fd153f744d">

Okay... That's clear. Right now the only way I can see this working is if the storage service (and thus, the `BrowserEnvironmentService` + `IFileService` + `ILogService` + `IUriIdentityService` + `IUserDataProfilesService` + `IUserDataProfileService`) are initialized "manually" via their constructor, and then passed to the resulting service collection. It's definitely possible. These services don't need more than the environment configuration + workspace path, and then they should work. Of course the question is if we can introduce this without that complexity + added services to the user?

**Comment by CompuIves** [comment]
Or, the other approach is that we patch `standaloneServices` to not do this code:

```ts
		// Instantiate all editor features
		const editorFeatures = getEditorFeatures();
		for (const feature of editorFeatures) {
			try {
				instantiationService.createInstance(feature);
			} catch (err) {
				onUnexpectedError(err);
			}
		}
```

And we call it manually after we've done the lifecycle startup.

**Comment by CompuIves** [comment]
I've opened a PR that takes the approach of my last comment. I'm not saying that it's _the_ way, but it's an approach that could work.

**Comment by CGNonofr** [comment]
Good job!

As an alternative, to be even more close to vscode, you can even remove the editor feature instantiations from the service initialization, and import `vs/workbench/contrib/codeEditor/browser/editorFeatures.ts` from monaco.ts

**Comment by CGNonofr** [comment]
There is also an issue on the demo that changes the theme after the services are initialized, I fixed everything in https://github.com/CodinGame/monaco-vscode-api/pull/235, I hope you don't mind
