### ISSUE TITLE
`monaco-treemending` deleting `edcore.main.js`

### ISSUE THREAD

**Issue by char0n** [CodinGame/monaco-vscode-api#234]
I've noticed that `monaco-treemending` script is removing `esm/vs/editor/edcore.main.js` file. I use this entrypoint to simulate API of https://www.npmjs.com/package/monaco-editor-core.

Is it by design?

**Comment by CGNonofr** [comment]
The patch is created between the output of the vscode monaco build process not treeshaken (so monaco-editor-code treemended) and the official monaco-editor. So if monaco-editor adds some files compared to monaco-editor-core, there's change they will be removed. What do you mean by `to simulate API of https://www.npmjs.com/package/monaco-editor-core`?

**Comment by char0n** [comment]
I'm using following webpack@5 alias to avoid pulling following imports into the bundle:

**Webpack alias:**
```js
// This alias doesn't pull any languages into bundles and works as monaco-editor-core was installed
'monaco-editor$': 'monaco-editor/esm/vs/editor/edcore.main.js',
```

**Unwanted languages:**
```js
import '../language/css/monaco.contribution';
import '../language/html/monaco.contribution';
import '../language/json/monaco.contribution';
import '../language/typescript/monaco.contribution';
```

**Comment by CGNonofr** [comment]
When using monaco-vscode-api, you don't need those aliases

**Comment by char0n** [comment]
> When using monaco-vscode-api, you don't need those aliases

Could you elaborate maybe why? Thanks!

**Comment by CGNonofr** [comment]
Cause of that treemending script that already removes monaco-specific features
