### ISSUE TITLE
Services with 1.86.6 version produce error

### ISSUE THREAD

**Issue by BusinessDuck** [CodinGame/monaco-vscode-api#245]
When i update from 1.86.5 to 1.86.6 the error appear (langauge client also 7.0.1):

```
t Module.ok (assert.js:22:1)
    at RegistryImpl.add (platform.js:14:1)
    at eval (editor.js:317:1)
    at ./node_modules/.pnpm/@codingame+monaco-vscode-api@1.83.5/node_modules/@codingame/monaco-vscode-api/vscode/src/vs/workbench/common/editor.js (vendors-node_modules_pnpm_codingame_monaco-vscode-api_1_83_5_node_modules_codingame_monaco-vs-b6ede8.js:92:1)
    at __webpack_require__ (runtime.js:31:42)
    at eval (editorGroupsService.js:15:75)
    at ./node_modules/.pnpm/@codingame+monaco-vscode-api@1.83.5/node_modules/@codingame/monaco-vscode-api/vscode/src/vs/workbench/services/editor/common/editorGroupsService.js (vendors-node_modules_pnpm_codingame_monaco-vscode-api_1_83_5_node_modules_codingame_monaco-vs-b6ede8.js:197:1)
    at __webpack_require__ (runtime.js:31:42)
    at eval (editorService.js:9:81)
    at ./node_modules/.pnpm/@codingame+monaco-vscode-api@1.83.5/node_modules/@codingame/monaco-vscode-api/vscode/src/vs/workbench/services/editor/common/editorService.js (vendors-node_modules_pnpm_codingame_monaco-vscode-api_1_83_5_node_modules_codingame_monaco-vs-b6ede8.js:204:1)
```

**Comment by BusinessDuck** [comment]
<img width="664" alt="image" src="https://github.com/CodinGame/monaco-vscode-api/assets/10143411/cd2ab05e-bde2-46ab-86b1-df514b42ac66">

package.json listing
```
"vscode": "npm:@codingame/monaco-vscode-api@>=1.83.7 <1.84.0",
"@codingame/monaco-vscode-configuration-service-override": "~1.83.7",
"@codingame/monaco-vscode-keybindings-service-override": "~1.83.7",
"@codingame/monaco-vscode-model-service-override": "~1.83.7",
"monaco-editor": "npm:@codingame/monaco-editor-treemended@>=1.83.7 <1.84.0",
"monaco-languageclient": "7.0.1",
  "overrides": {
      "monaco-editor": "npm:@codingame/monaco-editor-treemended@>=1.83.7 <1.84.0"
    },
    "resolutions": {
      "monaco-editor": "npm:@codingame/monaco-editor-treemended@>=1.83.7 <1.84.0"
    }

```

**Comment by BusinessDuck** [comment]
Error is appear because inside of package `monaco-languageclient ~ 7.0.1` deps are incorrect:

```
<img width="716" alt="image" src="https://github.com/CodinGame/monaco-vscode-api/assets/10143411/67610cb6-59d2-4156-9d4e-f2ffa1f99578">
```

**Comment by kaisalmen** [comment]
You have to add `"vscode": "npm:@codingame/monaco-vscode-api@>=1.83.7 <1.84.0",` to your overrides

**Comment by BusinessDuck** [comment]
Seems like it does not help, i also tried with resolutions, didn't works :( I'll wait for package update 💪

**Comment by BusinessDuck** [comment]
We're have in production monaco-editor with 0.37 version, bacause infrastructure science this version becomes unstable, i talking about @codingame and lsp packages which you maintain. It's really find and you do the great job. But now we need to create stable product, would be nice if team keep focus on infrastructure stability and stop working on new features relates to infrastructure changes.

**Comment by CGNonofr** [comment]
Please keep in mind that nobody works for you here. Feel free to contribute if you feel like it to improve the `infrastructure stability` (whatever that means)

**Comment by BusinessDuck** [comment]
We could try to collaborate more closely, but I am not clear about the open issues of the project if you were working in the Github issue. I could see unsolved issues and try to make pull requests. 

Consider making infrastructure tasks public and creating a monorepository for work so that releases are more synchronous and don't cause collisions across a large number of packages.

**Comment by digitallyserviced** [comment]
@BusinessDuck
I am sorry I have to make sure that this is mentioned, because people really dont think about how much value you sometimes get and end up taking for granite(lol).

I want to credit @CGNonofr and actually make sure that people are aware of his commitment ( in monetary and real-life terms) in case anyone is not actually aware of it... 

this is an open-source, free, no support contract included, 0% SLA, super-fork of a Microsoft monolith, ripped to shreds to offer better and uncoupled abilities, that fortunately has a main developer, who is actually responding to you FASTER than most support contracted, 99.999% SLA enterprise contracts at $1000000/year...   (he replied within ~5min, 99.999% uptime allows for ~5min downtime/5hr response time a month)

This is a product that you are able to fork, freeze with goal of an LTS, create PRs to establish necessary req's, work on them yourself, WITH a developer who isn't a ghost/hermit/figment to possibly answer questions/offer support/guidance, and even possibly push keys for $...

This is open, yes
it has some goals, yes
your goals? no

but that doesn't matter, because you have access, can use old versions, tailor current ones, and just basically take,take,take any pieces you want to get the stability and infrastructure that WILL work for you, from something would assume @CGNonofr has spent more than 1 year of thinkable time to produce...

**Comment by CGNonofr** [comment]
Very heartwarming message!

I'm probably the most active dev here, but it would be really unfair to not mention @kaisalmen who has provided a lot of support (and I hope will continue to) and who has seen their library monaco-languageclient depleted of its essence slowy as this lib became more VSCode compliant

**Comment by kaisalmen** [comment]
@CGNonofr thank you. Still recovering. Will continue to support this if I can keep up with the changes you and @CompuIves put out. 👀 💪 Regarding monaco-languageclient everything evolved the right way. No regrets there.

**Comment by BusinessDuck** [comment]
I don't understand your concerns. Expectations from the open source project: everyone will participate and help vs reality: spelling corrections in the readme. For this to work, you need to create an open process on your part, designate a roadmap. You guys don’t do this, this is your mistake, your processes and plans are closed from the outside world. Take a look at https://github.com/microsoft/vscode/wiki/Roadmap.

You are creating users for yourself, not fellow developers with your approach. At the same time, users give you feedback that the infrastructure in the last few versions is extremely unstable, many bugs appear, it is worth paying attention to this.

**Comment by BusinessDuck** [comment]
I recommend that you create an issue with the type "need help", these issues should describe specific tasks. Which will be part of the roadmap, then developers will be able to participate in solving these issues.

**Comment by CGNonofr** [comment]
We don't have nor need roadmap, we are just following VSCode as they integrate their roadmap while doing our best effort to make the interaction with it as easy and robust as possible.

I'd really like to know what you mean by unstable infrastructure when talking about a library. I really don't think "many but appeared" recently but we can maybe find a way to prevent them to appear at all by adding tests.

What should be put in that "need help" issue ?
