### ISSUE TITLE
Demo: Console log suddenly full of errors

### ISSUE THREAD

**Issue by kaisalmen** [CodinGame/monaco-vscode-api#259]
Latest main. I built it on my Ubuntu WSL as usual. And I just checked the [deployed version](https://codingame.github.io/monaco-vscode-api/) same there. Are you aware of this already?
![image](https://github.com/CodinGame/monaco-vscode-api/assets/21079138/5d464c79-f191-4b82-b415-0f3c8681f752)
![image](https://github.com/CodinGame/monaco-vscode-api/assets/21079138/4bc71403-d006-4d4c-baf9-47f6fa8e5beb)

**Comment by CGNonofr** [comment]
I wasn't! will check

**Comment by CGNonofr** [comment]
Are you able to reproduce locally? I'm not

**Comment by CGNonofr** [comment]
locally in the demo here I meant :)

**Comment by kaisalmen** [comment]
The same

**Comment by kaisalmen** [comment]
I build the main here (a726df138b3a1e75d46220fba9c576143d241107). The PR commit of #258. Not the one from #252

**Comment by CompuIves** [comment]
I just noticed this too with an upgrade. For some reason disabling the snippet service made it work for me here, I can also help debug this end of day.

**Comment by CompuIves** [comment]
I've a theory, for me some issues were resolved yesterday after including https://github.com/CodinGame/monaco-vscode-api/blob/main/demo/vite.config.ts#L51-L64. I wonder if there's duplicate code.

**Comment by CGNonofr** [comment]
There is a limit while trying to inject dependencies to prevent infinite loop which is limited arbitrary to 1000. Changing it to 2000 fixes the issue so it looks like a race condition here

**Comment by CompuIves** [comment]
🤯

**Comment by CGNonofr** [comment]
Ok I'm able to reproduce locally, I wasn't up to date with the remote main. me = dumb

**Comment by CGNonofr** [comment]
I've created a PR on the VSCode side: https://github.com/microsoft/vscode/pull/199037

and the PR here: https://github.com/CodinGame/monaco-vscode-api/pull/260

**Comment by kaisalmen** [comment]
@CGNonofr superb! Thank you.
