### ISSUE TITLE
Did the latest fix break exports? 

### ISSUE THREAD

**Issue by kaisalmen** [CodinGame/monaco-vscode-api#263]
I upgraded to `1.83.12` and something like this is no longer compiling:
```ts
import * as vscode from 'vscode';

export class MyProvider implements vscode.DocumentSymbolProvider {
...
```
Did I miss something or did something break?

**Comment by CGNonofr** [comment]
What is the error? I see nothing wrong on my side

**Comment by kaisalmen** [comment]
Sorry, seems to be some dependency/overrides problem. Will come back to you.

**Comment by kaisalmen** [comment]
My fault. Upgrade went wrong.

**Comment by kaisalmen** [comment]
@CGNonofr FYI, the actual problem was that I fracked up the `@types/vscode` version and then everything fell apart.
