### ISSUE TITLE
How do I enable only problems panel tab?

### ISSUE THREAD

**Issue by levensta** [CodinGame/monaco-vscode-api#265]
I use pure monaco-editor with its own settings and language validation. I want to add the ability to open a panel that displays a list of markers with errors, but I have not found anyone trying to solve this problem

<img width="604" alt="image" src="https://github.com/CodinGame/monaco-vscode-api/assets/64372619/acf9d01c-911e-4892-98f0-dd9a153c8304">

The `monaco-vscode-api` looks like something that might help me, but I looked at the [demo](https://github.com/CodinGame/monaco-vscode-api/tree/main/demo) in the repository and I'm afraid it's too big a package for a single feature with a panel tab.

How to properly install and configure `monaco-vscode-api` so that only the problems panel tab is used, so as not to load the bundle with extensions that won't be used?

**Comment by CGNonofr** [comment]
I'm afraid that you won't be able to only display the marker panel without pulling anything else for some reasons:
- You may notice that the markers panel includes a header displayed in the tab section and the panel part, I don't know how it would work in standalone
- The panel part and services are managing the panel lifecycle (visible or not, its layout...)

What you can do is only using the `view` and `marker` service overrides and rendering only the panel part though if the bundle size is not a blocking problem

**Comment by CGNonofr** [comment]
probably the view service override won't work without some other services override, like the configuration service override. It's hard to know all working combinations
