### ISSUE TITLE
Regression related to semantic tokens

### ISSUE THREAD

**Issue by char0n** [CodinGame/monaco-vscode-api#268]
Hello,

I've noticed that `@codingame/monaco-vscode-api@=1.83.6` has some kind of regression when related to Semantic Tokens Provider. Here is how I use the provider. 

```js
import { languages as vscodeLanguages } from 'vscode';

vscodeLanguages.registerDocumentSemanticTokensProvider(
  languageId,
  new DocumentSemanticTokensProvider(...args),
  semanticTokensLegend
);
```

`DocumentSemanticTokensProvider.prototype.provideDocumentSemanticTokens` is called in `@codingame/monaco-vscode-api@=1.83.5` but not called in `@codingame/monaco-vscode-api@>=1.83.6`. I couldn't figure out why it doesn't work.

The code in question is in https://github.com/swagger-api/swagger-editor/tree/next.

Any help would be appreciated. Thank you!

**Comment by CGNonofr** [comment]
Did you try with the last version?

It's probably just a duplicated dependency somehow

**Comment by char0n** [comment]
I did. Delete the `node_modules` and webpack cache as well.

**Comment by CGNonofr** [comment]
Do other language providers still work? are you able to reproduce in the demo here? (I'm not)

**Comment by char0n** [comment]
One have one language `apidom` which handles multiple specifications languages (OpenAPI, AsyncAPI,...) under the hood via Language Server. It just worked before, I haven't done any changes to the code, except to update the vscode API.

**Comment by cdietrich** [comment]
in my tests it still is working with `1.83.12`

**Comment by cdietrich** [comment]
can you provide a simple reproducer?

**Comment by char0n** [comment]
> can you provide a simple reproducer?

That would take some time. I'll try to debug before I'll fallback to building a minimal repro

After debugging the `exHostLanguageFeatures.js` I can say the following:

- `registerDocumentSemanticTokensProvider` is called and provider is registered successfully
- `$provideDocumentSemanticTokens` is never called

**Comment by char0n** [comment]
@CGNonofr, @cdietrich: the simplest steps of reproduction are:

```js
import * as monaco from 'monaco-editor';

monaco.languages.registerDocumentSemanticTokensProvider('apidom', {
  getLegend() {
    console.dir('legend');
    return [];
  },
  provideDocumentSemanticTokens() {
    console.dir('providing');
    return [];
  },
});
```

This simple provider works in `@codingame/monaco-vscode-api@=1.83.5` but doesn't work in `@codingame/monaco-vscode-api@>=1.83.6`. It's like tree-mending removed some code that made monaco-editor call the provider methods.

**Comment by CGNonofr** [comment]
Ok there is multiple issues indeed:
- models created before the first editor are not taken into account for editor feature (VSCode bug)
- the editor features are not registered if `vscode/monaco` is not imported

fix incomming

**Comment by CGNonofr** [comment]
after the update, do not forgot to reapply the treemending patch (by running `npm ci`)

note that as soon as you use monaco-vscode-api, calling `initialize` from `vscode/services` is mandatory (even without any service) to run workbench contributions (that includes editor features like semantic tokens)

**Comment by char0n** [comment]
@CGNonofr thanks for the fix. 

> after the update, do not forgot to reapply the treemending patch (by running npm ci)

Yep, that's what I'm doing. I'm event deleting `node_modues/` before the update as I want to run tree-mending on fresh `monaco-editor` install just to be sure.

> note that as soon as you use monaco-vscode-api, calling initialize from vscode/services is mandatory (even without any service) to run workbench contributions (that includes editor features like semantic tokens)

Yep, calling initialize explicitly before doing anything else.
