### ISSUE TITLE
Any insight on this error?? unhandled method window/workDoneProgress/create

### ISSUE THREAD

**Issue by eye-horus** [CodinGame/monaco-vscode-api#297]
I'm getting this error throw from the monaco editor client when I tried to use it with typescript language server.

**Error:**
Unhandled method window/workDoneProgress/create

Looks like the client editor is advertising it has workDoneProgress capabilities, but its not handling the above message from the server.

<img width="372" alt="image" src="https://github.com/CodinGame/monaco-vscode-api/assets/28602033/0620aa83-8dbb-4498-9e53-0b7e6e677142">

Really appreciate any insights into this, thank you

**Comment by CGNonofr** [comment]
Are you using `monaco-languageclient`?

**Comment by CGNonofr** [comment]
related to https://github.com/TypeFox/monaco-languageclient/issues/586
