### ISSUE TITLE
How to add d.ts file

### ISSUE THREAD

**Issue by aiselp** [CodinGame/monaco-vscode-api#301]
The following method worked in previous versions, but it doesn't work now
```js
monaco.languages.typescript.javascriptDefaults.addExtraLib()
```

**Comment by CGNonofr** [comment]
Are you using the Monaco contribution or the VSCode extension? That method only works with the first one

**Comment by aiselp** [comment]
I seem to be using the 2nd option，Is there any way to achieve the same effect?

**Comment by CGNonofr** [comment]
Then it works the same way as un VSCode, so put the file un the workspace and reference it from the tsconfig

**Comment by jpdery** [comment]
Is there an example on how to do this ?
