### ISSUE TITLE
Display problem in "Peek" mode

### ISSUE THREAD

**Issue by Tnze** [CodinGame/monaco-vscode-api#305]
Please watch the video:

https://github.com/CodinGame/monaco-vscode-api/assets/19628575/436af707-2898-4b4f-9770-c69e7c0f6ae6

1. The peeked file doesn't shown before resizing.
2. The split panel is weird.

**Comment by Tnze** [comment]
It seems to have a very small size in the upper left corner, before I resize the editor.

**Comment by CGNonofr** [comment]
What a weird bug!

Are you sure it's related to that library? the peek component is included in monaco itself

**Comment by ndeyefatoudiop1993** [comment]
I have also noted this issue with the Monaco editor when you try to peek a definition. The fix was to either wait for the definitions to be loaded or apply some css to the editor so it takes full width/height

**Comment by Tnze** [comment]
> wait for the definitions to be loaded

How do I wait for the definitions to be loaded?

**Comment by ndeyefatoudiop1993** [comment]
> > wait for the definitions to be loaded
> 
> How do I wait for the definitions to be loaded?

It depends on how you get the definitions. When I use for example [vscode-languageclient](https://github.com/microsoft/vscode-languageserver-node), I can use the middleware and intercept when the definitions are received from the language server. Then I make sure that the files for the definitions are actually loaded. 

Else try to put a width/height of 100% on the element “.reference-inline-widget .inline”
