### ISSUE TITLE
vite configuration error

### ISSUE THREAD

**Issue by aiselp** [CodinGame/monaco-vscode-api#306]
This is the configuration of my vite.config.ts. I don’t know what the uri is. The resolve attribute does not exist in import.meta.
![image](https://github.com/CodinGame/monaco-vscode-api/assets/76829457/f66467bd-3ca0-45a2-b465-fc8bf1ec5326)

I get the following error when trying to start the development server
![image](https://github.com/CodinGame/monaco-vscode-api/assets/76829457/c2595731-a74d-4583-a31a-18b4ed0ec21a)

**Comment by cemalgnlts** [comment]
Did you use this flag: `--experimental-import-meta-resolve`

https://github.com/CodinGame/monaco-vscode-api/blob/main/demo/package.json#L10
