### ISSUE TITLE
Multiple Status Bar Item

### ISSUE THREAD

**Issue by cemalgnlts** [CodinGame/monaco-vscode-api#307]
Hi,

I created a status bar item to open notifications:
```js
await initialize({
  ...
});

// Notification status bar item.
const notifyService = await getService(INotificationService);

const getIcon = (dotIcon: boolean = false) => {
  const icon = ["bell"];

  if (notifyService.doNotDisturbMode) icon.push("-slash");
  if (dotIcon) icon.push("-dot");

  return `$(${icon.join("")})`;
};

const notifyItem = window.createStatusBarItem(StatusBarAlignment.Right, 1);
notifyItem.command = "notifications.showList";
notifyItem.name = "Notifications";
notifyItem.text = getIcon();

notifyService.onDidChangeDoNotDisturbMode(() => (notifyItem.text = getIcon()));
notifyService.onDidRemoveNotification(() => (notifyItem.text = getIcon()));
notifyService.onDidAddNotification(() => (notifyItem.text = getIcon(true)));

notifyItem.show();
```

This allows me to add a notification widget at the bottom right like in VSCode:
![Screenshot 2024-01-04 15 26 58](https://github.com/CodinGame/monaco-vscode-api/assets/45357531/e8b2490b-c429-41c3-8c25-e319d299d894)

I then try to create another one for my extension running in worker.
```js
import { StatusBarAlignment, commands, window } from "vscode";

function activate() {
  addStatusBarItem();

  commands.registerCommand("esbuild.test", () => {
    console.log("OK");
  });
}

function addStatusBarItem() {
  const item = window.createStatusBarItem(StatusBarAlignment.Left, 1);
  item.command = "esbuild.test";
  item.name = "esbuild";
  item.text = "$(zap) Build";
  item.show();
}

export { activate };
```

Instead of adding more than one place, they share one place.

[Screen recording 2024-01-04 15.34.03.webm](https://github.com/CodinGame/monaco-vscode-api/assets/45357531/d5ff6862-40a9-4aaa-902f-ffbfe71283e5)

**Comment by CGNonofr** [comment]
Indeed, it looks like a bug in VSCode, here's the bug report: https://github.com/microsoft/vscode/issues/201795

The workaround is to set the status bar item id

Here's the PR that adds the missing VSCode notification status bar item: https://github.com/CodinGame/monaco-vscode-api/pull/308
