### ISSUE TITLE
Unnecessary Files

### ISSUE THREAD

**Issue by cemalgnlts** [CodinGame/monaco-vscode-api#322]
Hi,

When I built my project in the latest version, I realized that there were files that did not exist before.

For example, a markdown file is being added:
![Screenshot 2024-01-20 12 50 59](https://github.com/CodinGame/monaco-vscode-api/assets/45357531/2a0fa09f-bda5-4b9b-8914-6cca221e25e8)

Diagnostics JSON files:
![Screenshot 2024-01-20 12 52 49](https://github.com/CodinGame/monaco-vscode-api/assets/45357531/0ac1bf92-2c12-44af-8e5c-b48e71f4ec25)

And I'm not sure where this icon is used:
![Screenshot 2024-01-20 12 55 32](https://github.com/CodinGame/monaco-vscode-api/assets/45357531/31883bc0-3b1b-4c47-b50f-c19a1e44d38e)

**Comment by CGNonofr** [comment]
Yes, in the last version, the build process of extensions has been changed to stop filtering extension files that should be bundled. It was a hazardeous process that became even harder after the last change minimizing extension codes.

Is that an issue for you? The only consequence I see is the build time maybe a little longer and the bundled size a little bigger, but those files won't get loaded in the client

**Comment by cemalgnlts** [comment]
> Is that an issue for you?

Not, really.

**Comment by CGNonofr** [comment]
Useless files from extension without code should not be bundled anymore with the last version
