### ISSUE TITLE
[Feature Request] MenuRegistry

### ISSUE THREAD

**Issue by cemalgnlts** [CodinGame/monaco-vscode-api#323]
Hi,

Here I found MenuRegistry: https://github.com/microsoft/vscode/blob/564d6ae4c7c0e1158d3d6bd15d925a0c4430ecaf/src/vs/workbench/browser/parts/titlebar/menubarControl.ts#L47, but when I try to use it, it can't find it in `vs/platform/actions/common/actions`.

It also performs a check when adding default menus in this file: https://github.com/microsoft/vscode/blob/564d6ae4c7c0e1158d3d6bd15d925a0c4430ecaf/src/vs/platform/menubar/electron-main/menubar.ts#L292

I thought maybe enabling these two features could help to customize the menu and remove some menu items.

I tried to add at least `vs/platform/actions/common/actions` but without much success.

**Comment by cemalgnlts** [comment]
It looks like menubar.ts file for electron.

**Comment by CGNonofr** [comment]
This library currently bundles only the services designed for the web version of VSCode  supporting electron is planned but not really a priority

**Comment by cemalgnlts** [comment]
Yes, I thought maybe it would work to customize the menu, I realized later that it was electron. What do you think about MenuRegistry.

**Comment by cemalgnlts** [comment]
Do I need to override (or implement) the action service for `MenuRegister`?
