### ISSUE TITLE
Uncaught TypeError: this._fileService.onWillActivateFileSystemProvider is not a function

### ISSUE THREAD

**Issue by caleb1248** [CodinGame/monaco-vscode-api#337]
I was following the demo, and I got this error:
`Uncaught TypeError: this._fileService.onWillActivateFileSystemProvider is not a function`

The error seems to be coming from the extension service override.

My code is [here](https://github.com/caleb1248/monaco-editor-testing/tree/5d0b02e05e0de9872ebba29ed7d479aaa958ab15)

![image](https://github.com/CodinGame/monaco-vscode-api/assets/94559723/7c42d8d4-2c51-4bfb-8a62-71e57fe93463)

**Comment by CGNonofr** [comment]
You are mixing v1.85 packages with the next 2.0 packages. Please use last version for every packages
