### ISSUE TITLE
TypeScript Intellisense Not Working Across Files

### ISSUE THREAD

**Issue by Abdallatif** [CodinGame/monaco-vscode-api#360]
Hi! I've been trying to get TypeScript Intellisense to work with multiple files using the demo, but it's not happening. I added a tsconfig file thinking it might help, but no luck there either.

My main goal is to export a function from one file and have VSCode suggest to auto-import it. After that, I want to make sure VSCode can see the node_modules I install and check types correctly.

I saw this project called [jside](https://github.com/cemalgnlts/jside) that seems to have everything working, including TypeScript Intellisense. They're doing something different with how files are set up, I think, but I can't figure out exactly what makes it work there and not in my case - demo project.

Any ideas on what I might be missing or doing wrong?

**Comment by Abdallatif** [comment]
Thanks a lot, this was very helpful. Adding the headers fixed the intellisense across files issue for me and the node_modules work out of the box now - except for a few issues.

btw, do you know why `extensionHost.worker.js` tries to call the npm registry for every module under `node_modules` folder? Like for example if I have the `uuid` module, it would send a GET request to https://registry.npmjs.org/uuid. This is causing some issues since I have private modules mounted under node_modules but the worker keeps trying to call the npm registry and npm reject the request!

**Comment by CGNonofr** [comment]
The npm default extensions calls registry.npmjs.org to get some metadata about packages that are used in the project, are you using it?

**Comment by Abdallatif** [comment]
I don't have the npm extensions installed. I tried to install it and set `npm.fetchOnlinePackageInfo` to false but it didn't change anything!

**Comment by CGNonofr** [comment]
Then I'm not able to reproduce nor seeing any code from this repo referencing registry.npmjs.org

Can you provide a simple reproduction repo?

**Comment by CGNonofr** [comment]
It looks like it's not an issue with this library but with the VSCode typescript extension then, right?

**Comment by cemalgnlts** [comment]
Yes, that's right, VSCode did not complete this feature in the web version of the extension. 

*(You must disable ATA so that types are not downloaded automatically: https://github.com/cemalgnlts/jside/blob/main/src/workspace/userConfiguration.json#L38)*

**Comment by Abdallatif** [comment]
@cemalgnlts Yeah, and I tried to [do that](https://github.com/Abdallatif/monaco-vscode-api/commit/afa5d7ca23603653cfe5387d1b53de7dbbf23934#diff-a7a1213dbb11be37bb74b32bcc1ad619a9b3c3f707f164001835c281631cf1dcR24) but the extension fetches the types anyway!

**Comment by cemalgnlts** [comment]
Sometimes (maybe because of the way I use it) when I delete IndexedDB and refresh the page, the configuration file starts working correctly.

**Comment by Abdallatif** [comment]
I was able to disable this behavior by commenting out this subscription https://github.com/microsoft/vscode/blob/main/extensions/typescript-language-features/src/extension.browser.ts#L108

Do you think this is something that should be patched in this package? I understand if it's not and I can publish my changes under a different package.

**Comment by CGNonofr** [comment]
> I was able to disable this behavior by commenting out this subscription https://github.com/microsoft/vscode/blob/main/extensions/typescript-language-features/src/extension.browser.ts#L108
> 
> Do you think this is something that should be patched in this package? I understand if it's not and I can publish my changes under a different package.

Probably not. It's not a bug but a feature you don't want

**Comment by cemalgnlts** [comment]
I discovered that you can force it to read using `declare module` and including all `*.d.ts` files in the `node_modules` folder.

[Screen recording 2024-03-14 12.28.56.webm](https://github.com/CodinGame/monaco-vscode-api/assets/45357531/7d710558-88f8-4593-99e9-974ed5369bf6)
