### ISSUE TITLE
Missing `initialize` from `vscode/extensions` in "^v1.83.15" causes error in monaco-languageclient "^6.6.1"

### ISSUE THREAD

**Issue by kfreezen** [CodinGame/monaco-vscode-api#372]
This issue has been raised once, in #283, however, it seems that monaco-languageclient 6.6.1 depends on initialize being defined in `vscode/extensions`

Could a shim be added back in to keep compatibility with `monaco-languageclient ^6.6.1`?

Thanks! Or perhaps there is another workaround to be used that you might suggest.

**Comment by kfreezen** [comment]
I'd like to add that I am aware this is an out of date version, but I'm working on getting an old piece of code using Monaco / monaco-languageclient from the Stone Age too something more modern, and this would be quite helpful, if not to me, then to others facing the same issue.

In the meantime I will work around by pinning to v1.83.14 in my project dependencies.

**Comment by CGNonofr** [comment]
This library api gets more and more stable over time and you are referring to a time when it was often changing. And we were releasing every version as a patch version...

It should not happen in the future but I don't think we'll be able to do anything regarding old versions

**Comment by kfreezen** [comment]
Thanks for the response. I'll close this issue. Hopefully this workaround saves someone else a few hours of time.

**Comment by kfreezen** [comment]
Workaround in package.json

```json
{
  "dependencies": {
    "vscode": "npm:@codingame/monaco-vscode-api@==1.83.14",
   }
}
```
