### ISSUE TITLE
CMD+Z on swedish keyboard working not well

### ISSUE THREAD

**Issue by toastyboost** [CodinGame/monaco-vscode-api#379]
Hi guys! CMD+Z shortcut on Swedish keyboard in Chrome feels bad - its cancel last action only by one character in one line and not a whole word as before

Is anyone familiar with the problem?

**Comment by CGNonofr** [comment]
Do you have the same issue on vscode.dev?

**Comment by dvangonen** [comment]
Yes, the same issue on vscode.dev

**Comment by CGNonofr** [comment]
Then please report it on [vscode repo](https://github.com/microsoft/vscode/issues) directly
