### ISSUE TITLE
Publish the php-language-features extension.

### ISSUE THREAD

**Issue by ethan-vanderheijden** [CodinGame/monaco-vscode-api#381]
The php syntax highlighting extension has been published under `@codingame/monaco-vscode-php-default-extension`, but its corresponding language features package hasn't been published yet. For reference, PHP language features is a default vscode extension (https://github.com/microsoft/vscode/tree/main/extensions/php-language-features). Would it be possible to publish it?

**Comment by CGNonofr** [comment]
It is a default extension but I don't think it's web compatible, is it?

**Comment by ethan-vanderheijden** [comment]
Oh shoot, I hadn't realized it wasn't web-compatible.
