### ISSUE TITLE
Color picker was broken

### ISSUE THREAD

**Issue by BusinessDuck** [CodinGame/monaco-vscode-api#390]
Hi guys! In last release we have broken color picker functionality. In case when user change color it does not applied automatically.

https://monaco-vscode-api.netlify.app/

![image](https://github.com/CodinGame/monaco-vscode-api/assets/10143411/bd4ffd16-14dd-4b48-a2bd-7f89a20947f2)

**Comment by CGNonofr** [comment]
Well spotted, thanks for the report!
