### ISSUE TITLE
Separating View Welcome and Welcome Walkthorugh Services.

### ISSUE THREAD

**Issue by cemalgnlts** [CodinGame/monaco-vscode-api#394]
Hi,

If we use the Welcome Service Override package, these two services are added:
* https://code.visualstudio.com/api/references/contribution-points#contributes.viewsWelcome
* https://code.visualstudio.com/api/references/contribution-points#contributes.walkthroughs

If I only want to use the `viewsWelcome` service, the `walkthroughs` service is included, which I don't need at all.

I don't know if it is possible, but it could be very useful to separate these two packages.

**Comment by CGNonofr** [comment]
Sure, looks like a good idea
