### ISSUE TITLE
`_webviewIframeAlternateDomains` is tree-shaken away in workbench

### ISSUE THREAD

**Issue by CompuIves** [CodinGame/monaco-vscode-api#398]
When you look at the output of `@codingame/monaco-vscode-workbench-service-override` on line 136 (right here: https://unpkg.com/browse/@codingame/monaco-vscode-workbench-service-override@4.3.0/workbench.js), you can see that nothing is done with `_webviewIframeAlternateDomains`. Because of this, the argument is ignored and webviews are created on the root domain.

**Comment by CGNonofr** [comment]
You're right... WTF is rollup doing Oo

The funny part is there is the exact same code in the views service override and this one is kept!

**Comment by CGNonofr** [comment]
Hum... Ok, found the issue :grin:

**Comment by CompuIves** [comment]
Wow, that's quick!

**Comment by CGNonofr** [comment]
It's pretty obvious, try to find the difference between views and workbench ;)

**Comment by CompuIves** [comment]
Sneaky! Well, in that case the optimization makes sense 😅
