### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by BusinessDuck** [CodinGame/monaco-vscode-api#401]
Local build isn't work. I am follow this guide https://github.com/CodinGame/monaco-vscode-api?tab=readme-ov-file#demo

On step `npm run build` i see this:
<img width="1119" alt="image" src="https://github.com/CodinGame/monaco-vscode-api/assets/10143411/2aadcabd-12c0-4a68-a659-8eaad1d8150f">

Then after demo start this hapen

![image](https://github.com/CodinGame/monaco-vscode-api/assets/10143411/2a234db0-b4d5-470c-aa55-b0bafda74bea)

**Comment by BusinessDuck** [comment]
my node is out of date. Solved. Required node version 20.x.x

**Comment by CGNonofr** [comment]
Ok I was going to submit my answer :)

Note than we use [Volta](https://volta.sh/) in this project to manage npm/node version, it may be a good idea to have it
