### ISSUE TITLE
Could not resolve package

### ISSUE THREAD

**Issue by aiselp** [CodinGame/monaco-vscode-api#418]
![image](https://github.com/CodinGame/monaco-vscode-api/assets/76829457/3562b35b-8bcc-4e16-8f7f-516749e2f680)

![image](https://github.com/CodinGame/monaco-vscode-api/assets/76829457/7402080e-53e9-4d3e-b5e1-00b8abd46181)

The dependency versions used are as follows：
![image](https://github.com/CodinGame/monaco-vscode-api/assets/76829457/2eaf3f9a-a8a7-45b6-8246-b64d8c7829e5)

**Comment by CGNonofr** [comment]
Thanks for the report! The fix is already on its way
