### ISSUE TITLE
"Reopen Editor With..." does not work for custom editors

### ISSUE THREAD

**Issue by CompuIves** [CodinGame/monaco-vscode-api#421]
To reproduce:

1. In the demo, open `test.customeditor`
2. Open the command palette
3. Select "Reopen editor with..."

It will throw an error, saying `unsupported`, because it's trying to call a function on a mock `EditorGroup`:

<img width="532" alt="image" src="https://github.com/CodinGame/monaco-vscode-api/assets/587016/a6f6674e-6ca9-40b9-ad3b-914b64dedfa6">

It looks like the custom editors contributed using the `registerCustomEditor` API have `EmptyEditorGroup` as its editor group. It used to work before, but I don't know exactly when it stopped working. I suspect somewhere before version 3.2.x.

**Comment by CompuIves** [comment]
Hmm, with the latest version in the demo I still see the same issue. The error of `EmptyEditorGroup` is gone, but nothing happens when selecting "Reopen Editor With..." on a custom editor. I think it's because the `group` is `null` in this case, because I also see a new kind of editor from the history service:

<img width="750" alt="Screenshot 2024-05-08 at 13 12 57" src="https://github.com/CodinGame/monaco-vscode-api/assets/587016/078adac7-e1fc-4404-b175-4ce9a85022d7">

Which corresponds to this code (line 182):

<img width="1113" alt="image" src="https://github.com/CodinGame/monaco-vscode-api/assets/587016/7e09dfb4-6a69-4379-bc64-75a5bf2e18ee">

**Comment by CGNonofr** [comment]
I don't know how it can work in your case, since it requires the input `toUntyped` method to be implemented to work
