### ISSUE TITLE
View Actions tooltips are not showing

### ISSUE THREAD

**Issue by Abdallatif** [CodinGame/monaco-vscode-api#422]
I've encountered an issue with tooltips not displaying for the actions within views toolbar. Specifically, tooltips appear correctly for main activities, such as hovering over the search icon which displays the "Search" tooltip. However, tooltips fail to appear for actions within the explorer view, like the 'New File' action.

The above issue happens in the default (attached views) mode, but it's working correctly in the full workbench mode.

I'm able to reproduce the issue in the [demo](https://monaco-vscode-api.netlify.app/) as well.

**Comment by CGNonofr** [comment]
Thanks for the report!

**Comment by Abdallatif** [comment]
@CGNonofr Thanks for working on this! It fixed the problem for most tooltips of the editor but the issue still there for actions in the title - like when there is only 1 view in a view container, the tooltips won't work.


https://github.com/CodinGame/monaco-vscode-api/assets/10572734/62fc4a7f-2536-4a38-bfbe-30b8e539aa9b
