### ISSUE TITLE
Vsix plugin doesn't work in dev mode

### ISSUE THREAD

**Issue by caleb1248** [CodinGame/monaco-vscode-api#438]
I installed the rollup vsix plugin and when importing it, I got this error: 
![image](https://github.com/CodinGame/monaco-vscode-api/assets/94559723/7cd715b6-ff1d-4d5b-9ebb-ca8d9bc4cd88)

It works fine when building for production though. How do I get the vsix plugin to work in dev mode?

**Comment by CGNonofr** [comment]
I've just checked and I'm unable to reproduce. Can you provide a minimal reproduction repo or at least the generated invalid code?

**Comment by caleb1248** [comment]
Here is my code: https://codesandbox.io/p/devbox/monaco-vscode-api-test-forked-jh4ntq

This line below causes the vite error screen in dev mode ("npm run dev").

```ts
import "./assets/theme.vsix";
```

However, no error is produced when running `npm run build`

**Comment by CGNonofr** [comment]
I've just forked and tried your sandbox, and I see no issue :thinking: 
![image](https://github.com/CodinGame/monaco-vscode-api/assets/23257479/b640790f-44f2-4a9e-9803-081b5fda743d)

Do you use a special env configuration or something? What is your operating system?

**Comment by caleb1248** [comment]
I have no special env configuration, and I have been making the app entirely in CodeSandbox (no local machine).
![image](https://github.com/CodinGame/monaco-vscode-api/assets/94559723/b37ad88e-aa0d-45fc-bd11-184287777c32)

**Comment by CGNonofr** [comment]
I see your error on your sandbox, but if I restart vite there is no error, either on linux or windows
