### ISSUE TITLE
@codingame/monaco-vscode-rollup-vsix-plugin: Missing @rollup/pluginutils dependency / peerDependency

### ISSUE THREAD

**Issue by ggoodman** [CodinGame/monaco-vscode-api#448]
When attempting to include `@codingame/monaco-vscode-rollup-vsix-plugin` as a vite plugin, vite complained that the module `@rollup/pluginutils` was not found.

I was able to work around this by adding `@rollup/pluginutils` as a devDependency of my own project but I believe that it should be either a `"dependency"` or `"peerDependency"` for `@codingame/monaco-vscode-rollup-vsix-plugin`.

**Comment by CGNonofr** [comment]
Thanks for the report!
