### ISSUE TITLE
Problem with custom theme declaration

### ISSUE THREAD

**Issue by SinnerAir** [CodinGame/monaco-vscode-api#458]
it is impossible to specify your theme through the method `monaco.editor.defineTheme`.

Version packages: 
-   "monaco-editor": "npm:@codingame/monaco-vscode-editor-api@^6.0.3",
-   "vscode": "npm:@codingame/monaco-vscode-api@^6.0.3",
-    "@codingame/monaco-vscode-theme-defaults-default-extension": "^6.0.3",
-   "@codingame/monaco-vscode-theme-service-override": "^6.0.3",
-   "@codingame/monaco-vscode-configuration-service-override": "^6.0.3"

Despite the fact that when moving a call various errors appear:

if before initialization: _Uncaught Error: Services are already initialized_
if after initialization: _monaco-editor.js?v=27546643:2315 Uncaught TypeError: standaloneThemeService.defineTheme is not a function_

Live demo: https://stackblitz.com/edit/stackblitz-starters-xqgvjd?file=script.js

**Comment by CGNonofr** [comment]
Indeed, `monaco.editor.defineTheme` can only be used to define monaco/monarch themes.

As soon as you use the theme service override, you are expected to use a VSCode extension to declare it.

**Comment by SinnerAir** [comment]
Thank you. I will try.

**Comment by SinnerAir** [comment]
Happened! Thank you
