### ISSUE TITLE
How to open a workspace?

### ISSUE THREAD

**Issue by abentkamp** [CodinGame/monaco-vscode-api#470]
By default, no workspace seems to be open. How can I open a workspace?

For instance:
```
  const wrapper = new MonacoEditorLanguageClientWrapper();
  const userConfig : UserConfig = {
    wrapperConfig: {
      editorAppConfig: {
        $type: 'extended',
        codeResources: {
          main: {
            text: 'print("Hello, World!")',
            uri: '/workspace/hello.py'
          }
        }
      }
    }
  };

  const htmlElement = document.getElementById('monaco-editor-root');
  await wrapper.initAndStart(userConfig, htmlElement);

  workspace.getConfiguration('editor').update('tabSize', 5)
```
yields:
```
Uncaught CodeExpectedError: Unable to write to Workspace Settings because no workspace is opened. Please open a workspace first and try again.
```

Here is an example repo: https://github.com/abentkamp/monacotest3/tree/workspace

Thanks for your help!

**Comment by CGNonofr** [comment]
I think it's more of a [monaco-languageclient](https://github.com/TypeFox/monaco-languageclient) question

**Comment by abentkamp** [comment]
You are right, this seems to be a problem in `monaco-languageclient`. I will open an issue there.

At least I figured out how to open a workspace without `monaco-languageclient` now. I have to pass the following as the third argument of the `initialize` function:
```
    {
      workspaceProvider: {
        trusted: true,
        async open () {
          return false
        },
        workspace: {
          workspaceUri: monaco.Uri.file('/workspace.code-workspace')
        }
      }
    }
```
The file extension `.code-workspace` seems to be crucial here. The file does not need to exist in any sense.
