### ISSUE TITLE
Can't rename files because of NoPermissions error

### ISSUE THREAD

**Issue by KornelijusS** [CodinGame/monaco-vscode-api#472]
Hey, I found an issue in my implementation, that your demo seems to have also. You can't rename files as the error get's thrown for NoPermissions. Does anyone know how to fix this? My implementation is almost the same, but I could just see how this issue would be resolved in your demo and the try to apply the same in mine. 
![image](https://github.com/user-attachments/assets/87a73643-19a4-4231-a19b-fc42afee77f3)

**Comment by CGNonofr** [comment]
Yes, `RegisteredFileSystemProvider` files can't be renamed, it's not a bug but a lack of feature

see https://github.com/CodinGame/monaco-vscode-api/issues/447

What is your use-case?

**Comment by KornelijusS** [comment]
Oh, sorry, didn't see that one. My use case is pretty simple I have a database with projects and load them when user select which one to work on. The user can do anything with the files. That means delete/cerate/rename files or folders. I guess for me also the solution would be to create a custom file provider. As I also registered an extension that overrider the saving events, but having a custom file provider would be better as I could implement that myself.

**Comment by CGNonofr** [comment]
yes, RegisteredFileSystemProvider is for basic use-cases, as soon as your want something more complex, I recommend creating your own filesystem provider

**Comment by KornelijusS** [comment]
Okay, thanks closing this one then.
