### ISSUE TITLE
Missing default syntax highlighting with monaco-vscode-editor-api

### ISSUE THREAD

**Issue by shivam6543** [CodinGame/monaco-vscode-api#473]
Hello Team,

I have a question regarding syntax highlighting. In the older version of `monaco-editor`, I used to get syntax highlighting out of the box. However, now that I'm using this version: `"monaco-editor": "npm:@codingame/monaco-vscode-editor-api@~7.0.7"`, I don't get any syntax highlighting for any language.

My question is: how can I get the default monaco-editor syntax highlighting?

```
import getMonarchServiceOverride from '@codingame/monaco-vscode-monarch-service-override'

const startClient = async (value, language, fileUri) => {
  await initServices({
    serviceConfig: {
      userServices: {
        ...getMonarchServiceOverride()
      }
    }
  })

  editor = monaco.editor.create(editorNode, {
      minimap: {
          enabled: false,
      },
      theme: 'vs-dark'
  })

  let editorModel = monaco.editor.createModel(
      value,
      language,
      monaco.Uri.file(fileUri)
  )

  editor.setModel(editorModel)

  initLspConnection('ws://localhost:8080')
}
```

Thank you for your help!

**Comment by CGNonofr** [comment]
There are 2 ways:
- Using the monaco-editor engine (monarch):
  - import `@codingame/monaco-vscode-standalone-languages`
  - register the monarch service override (optional)
- Using the VSCode engine (Textmate): 
  - register the textmate and theme service overrides
  - Set a VSCode theme (the `@codingame/monaco-vscode-theme-defaults-default-extension` package bundles the VSCode default ones)
  - Import your language extension (`@codingame/monaco-vscode-XXX-default-extension`)

**Comment by shivam6543** [comment]
@CGNonofr Thanks for your quick answer.

I have one question: What will happen if I register the Monarch service override? What exactly will it override? Is there any documentation where I can read more about it?

I think we register monarch register services like this. Am I right?:

```
import '@codingame/monaco-vscode-standalone-languages'
import getMonarchServiceOverride from '@codingame/monaco-vscode-monarch-service-override'

await initServices({
    serviceConfig: {
      userServices: {
        ...getMonarchServiceOverride()
      }
    }
  })
  ```

**Comment by shivam6543** [comment]
@CGNonofr NO, I'm using [monaco-languageclient ](https://github.com/TypeFox/monaco-languageclient/tree/main/packages/client)only, not it's [wrapper](https://github.com/TypeFox/monaco-languageclient/tree/main/packages/wrapper).

```js
import * as monaco from 'monaco-editor';
import { initServices } from 'monaco-languageclient/vscode/services';
import { MonacoLanguageClient } from 'monaco-languageclient';
import { WebSocketMessageReader, WebSocketMessageWriter, toSocket } from 'vscode-ws-jsonrpc';
import { CloseAction, ErrorAction, MessageTransports } from 'vscode-languageclient';
import '@codingame/monaco-vscode-standalone-languages'
import getMonarchServiceOverride from '@codingame/monaco-vscode-monarch-service-override'

const startClient = async (value, language, fileUri) => {
  await initServices({
    serviceConfig: {
      userServices: {
        ...getMonarchServiceOverride()
      }
    }
  })

  editor = monaco.editor.create(editorNode, {
      minimap: {
          enabled: false,
      },
      theme: 'vs-dark'
  })

  let editorModel = monaco.editor.createModel(
      value,
      language,
      monaco.Uri.file(fileUri)
  )

  editor.setModel(editorModel)

  initLspConnection('ws://localhost:8080')
}

const initLspConnection = (url: string): WebSocket => {
    const webSocket = new WebSocket(url);
    webSocket.onopen = () => {
        const socket = toSocket(webSocket);
        const reader = new WebSocketMessageReader(socket);
        const writer = new WebSocketMessageWriter(socket);
        const languageClient = createLanguageClient({
            reader,
            writer
        });
        languageClient.start();
        reader.onClose(() => languageClient.stop());
    };
    return webSocket;
};

const createLanguageClient = (transports: MessageTransports): MonacoLanguageClient => {
    return new MonacoLanguageClient({
        name: 'Sample Language Client',
        clientOptions: {
            // use a language id as a document selector
            documentSelector: ['json'],
            // disable the default error handler
            errorHandler: {
                error: () => ({ action: ErrorAction.Continue }),
                closed: () => ({ action: CloseAction.DoNotRestart })
            }
        },
        // create a language client connection from the JSON RPC connection on demand
        connectionProvider: {
            get: () => {
                return Promise.resolve(transports);
            }
        }
    });
};
```

**Comment by shivam6543** [comment]
@CGNonofr Even after importing the `@codingame/monaco-vscode-standalone-languages` package, syntax highlighting for any language is not working, and code completion for JavaScript is also not working. In the console, I got this warning:
```
Could not create web worker(s). Falling back to loading web worker code in main thread, which might cause UI freezes. Please see https://github.com/Microsoft/monaco-editor#faq

You must define a function MonacoEnvironment.getWorkerUrl or MonacoEnvironment.getWorker
```

It seems like it's not creating the worker needed to support syntax highlighting. Earlier, when I was using `monaco-editor` with `monaco-editor-webpack-plugin`, it was working. But now that I'm using this package (`"monaco-editor": "npm:@codingame/monaco-vscode-editor-api@~7.0.7"`) as an alias for `monaco-editor`, it has stopped working.

I'm using webpack to bundle my project. I'm aware of the [this section](https://github.com/CodinGame/monaco-vscode-api/?tab=readme-ov-file#monaco-editor-webpack-plugin) in the README, but earlier I was not passing options to `new MonacoWebpackPlugin()`. Do you have any idea how to make it work with `monaco-vscode-editor-api`?

**Comment by CGNonofr** [comment]
You can do something [like that](https://github.com/CodinGame/monaco-vscode-api/blob/b6af5e955fdab9fa140f6d923c695447b6a5143e/demo/src/setup.common.ts#L192-L210) (just keep the worker you need)

If you use webpack, it should work out of the box

**Comment by shivam6543** [comment]
Okay, thanks for sharing this!

So, to support features like code completion for JavaScript and TypeScript languages, I just need to import this library: `@codingame/monaco-vscode-standalone-typescript-language-features`, right?

Something like this:
```js
import "@codingame/monaco-vscode-standalone-typescript-language-features";

const workerLoaders: Partial<Record<string, WorkerLoader>> = {
  editorWorkerService: () => new Worker(new URL('monaco-editor/esm/vs/editor/editor.worker.js', import.meta.url), { type: 'module' }),
  typescript: () => new Worker(new URL('@codingame/monaco-vscode-standalone-typescript-language-features/worker', import.meta.url), { type: 'module' }),
  javascript: () => new Worker(new URL('@codingame/monaco-vscode-standalone-typescript-language-features/worker', import.meta.url), { type: 'module' }),
};

window.MonacoEnvironment = {
  getWorker: function (moduleId, label) {
    const workerFactory = workerLoaders[label];
    if (workerFactory != null) {
      return workerFactory();
    }
    throw new Error(`Unimplemented worker ${label} (${moduleId})`);
  }
};

```



> If you use webpack, it should work out of the box

You mean if I use webpack, then I don't need to do anything else after setting the `window.MonacoEnvironment` value, right?

One more thing: Is there any restriction on putting that code? Like, do I need to set the value of `window.MonacoEnvironment` before calling the `initService` or something like that?


Thanks again for the help!

**Comment by CGNonofr** [comment]
> @CGNonofr Okay, thanks for sharing this!
> 
> So, to support features like code completion for JavaScript and TypeScript languages, I just need to import this library: `@codingame/monaco-vscode-standalone-typescript-language-features`, right?
> 
> Something like this:
> 
> ```js
> import "@codingame/monaco-vscode-standalone-typescript-language-features";
> 
> const workerLoaders: Partial<Record<string, WorkerLoader>> = {
>   editorWorkerService: () => new Worker(new URL('monaco-editor/esm/vs/editor/editor.worker.js', import.meta.url), { type: 'module' }),
>   typescript: () => new Worker(new URL('@codingame/monaco-vscode-standalone-typescript-language-features/worker', import.meta.url), { type: 'module' }),
>   javascript: () => new Worker(new URL('@codingame/monaco-vscode-standalone-typescript-language-features/worker', import.meta.url), { type: 'module' }),
> };
> 
> window.MonacoEnvironment = {
>   getWorker: function (moduleId, label) {
>     const workerFactory = workerLoaders[label];
>     if (workerFactory != null) {
>       return workerFactory();
>     }
>     throw new Error(`Unimplemented worker ${label} (${moduleId})`);
>   }
> };
> ```

Yes, sounds good, you just may want some syntax highlighting as well?

> > If you use webpack, it should work out of the box
> 
> You mean if I use webpack, then I don't need to do anything else after setting the `window.MonacoEnvironment` value, right?

Yes, I meant the `new Worker(new URL('xxx', import.meta.url), { type: 'module' })` should work out of the box, unlike vite which have some issues with it

> One more thing: Is there any restriction on putting that code? Like, do I need to set the value of `window.MonacoEnvironment` before calling the `initService` or something like that?

The worker are created when they are first needed, so they probably just need to be defined before the first editor is created, but I don't see any reason to postpone the definition :thinking: 

> Thanks again for the help!

You're welcome

**Comment by rishipurwar1** [comment]
> Yes, sounds good, you just may want some syntax highlighting as well?

Yes, for syntax highlighting, I'm using this library: `import '@codingame/monaco-vscode-standalone-languages'`

```js
import '@codingame/monaco-vscode-standalone-languages';
import "@codingame/monaco-vscode-standalone-typescript-language-features";

const workerLoaders: Partial<Record<string, WorkerLoader>> = {
  editorWorkerService: () => new Worker(new URL('monaco-editor/esm/vs/editor/editor.worker.js', import.meta.url), { type: 'module' }),
  typescript: () => new Worker(new URL('@codingame/monaco-vscode-standalone-typescript-language-features/worker', import.meta.url), { type: 'module' }),
  javascript: () => new Worker(new URL('@codingame/monaco-vscode-standalone-typescript-language-features/worker', import.meta.url), { type: 'module' }),
};

window.MonacoEnvironment = {
  getWorker: function (moduleId, label) {
    const workerFactory = workerLoaders[label];
    if (workerFactory != null) {
      return workerFactory();
    }
    throw new Error(`Unimplemented worker ${label} (${moduleId})`);
  }
};
```
