### ISSUE TITLE
Localization broken after 7.1.1 release

### ISSUE THREAD

**Issue by castrob** [CodinGame/monaco-vscode-api#478]
Updating to release 7.1.1+ causes packages of localization provided by the README to provide wrong translations on components.

Localization pt-br - Release 7.1.0
![localization-pt-br-7-1-0](https://github.com/user-attachments/assets/6a34b517-561e-4bfb-a893-851d775170c7)

Localization pt-br - Release 7.1.1
![localization-pt-br-7-1-1](https://github.com/user-attachments/assets/9dd71fbc-29e2-4c50-938e-302d22b68750)

"Close" gets replaced by "Config tabs". The action keeps closing it normally...
All "split" actions now shows "Unpin" 

This is also occurring on https://monaco-vscode-api.netlify.app/?locale=pt-br and https://monaco-vscode-api.netlify.app/?locale=es that uses 8.0.0 release.

**Comment by CGNonofr** [comment]
Thanks for the quick report
