### ISSUE TITLE
Is it possible to switch the vscode npm package import source path?

### ISSUE THREAD

**Issue by banggx** [CodinGame/monaco-vscode-api#489]
When the js/ts code logic in vscode uses "import" to import the npm package, it is found that the package information will be automatically downloaded through fetch. Can the source location of this download be switched?

**Comment by CGNonofr** [comment]
Can you please clarify what you mean, which npm package are you talking about? what part of `js/ts code logic in vscode` are you talking about? Are you referring to the extension code?

**Comment by banggx** [comment]
For example, when I type "import" in the editor to introduce "React"
<img width="579" alt="image" src="https://github.com/user-attachments/assets/cd575183-d76e-4d0c-b2fd-ebe32869fd35">
The network panel will display information about automatically downloading "React" related packages, and corresponding code prompts will appear for the "React" package in the editor.
<img width="854" alt="image" src="https://github.com/user-attachments/assets/c37f5bc2-d07a-467c-8e4f-c935615cb279">
I hope this editor can switch to another installation path when installing dependencies。

**Comment by CGNonofr** [comment]
Ok, you are talking about the editor in your app containing typescript code!

Your configuration is still unclear to me, are you using the VSCode typescript extension, in web mode? then it needs `typescript.tsserver.web.typeAcquisition.enabled` to be true, is that what you did? It then seems to be downloading from `registry.npmjs.com`

Please tell me what you are doing
