### ISSUE TITLE
DebugServer exits when "Run and Debug" is triggered

### ISSUE THREAD

**Issue by kaisalmen** [CodinGame/monaco-vscode-api#494]
This used to work fine.
Shortly after you start the debug session on the client the server just quits:
```shell
Server started on port 5555 :)
Exiting...
Exiting...
```

Nothing spectacular in the browser console:
![image](https://github.com/user-attachments/assets/2f0e1138-6cda-4acd-b5cf-bf58b8c5d4dc)

Is there an easy way to activate more verbose logging in the server?

**Comment by CGNonofr** [comment]
I'm unable to reproduce.

You can have a look at the `debugServer.ts` script, it seems to be exiting as soon as there is a `uncaughtException`, maybe it swallows the error

**Comment by kaisalmen** [comment]
> You can have a look at the debugServer.ts script, it seems to be exiting as soon as there is a uncaughtException, maybe it swallows the error

I will. Thank you.

**Comment by kaisalmen** [comment]
@CGNonofr I added some debugging code in the exit handler, but it just works now. 🤷‍♂️  I reverted my changes and it works as it should. Nevermind. I have no bloody clue why it broke two days ago.
