### ISSUE TITLE
MemoryFile jsconfig.json

### ISSUE THREAD

**Issue by ZWQ652** [CodinGame/monaco-vscode-api#502]
![image](https://github.com/user-attachments/assets/4aa5dd88-6bf6-4a40-afb0-30019053deb1)
I hope to include a global type file in the JS file.
In a previous issue, it was mentioned that jsconfig. json can be added to the memory file to achieve this.
But what I wrote was not implemented

**Comment by CGNonofr** [comment]
I'll need more details:
- What are you using for the typescript intellisense?
- You show that the model exists (without its uri so I can't really check) but the important part if the filesystem
- Is the jsconfig.json at the root of the configured workspace folder?

**Comment by ZWQ652** [comment]
> I'll need more details: 我需要更多的细节:
> 
> * What are you using for the typescript intellisense?你使用什么来实现typescript的智能感知?
> * You show that the model exists (without its uri so I can't really check) but the important part if the filesystem你显示了模型的存在(没有它的uri，所以我无法真正检查)，但重要的部分是文件系统
> * Is the jsconfig.json at the root of the configured workspace folder?是jsconfig。在配置的工作空间文件夹的根目录下的Json ?

no LSP Server. use MemoryFileSystem.
![image](https://github.com/user-attachments/assets/48875b19-bd71-44cb-ac82-1d0e9c7731e8)

**Comment by CGNonofr** [comment]
What is providing the typescript/javascript intellisense?

**Comment by ZWQ652** [comment]
> What is providing the typescript/javascript intellisense?是什么提供了typescript/javascript的智能感知?

ts-language-features-extension
![image](https://github.com/user-attachments/assets/9eba0c94-bc2b-4095-846c-27f8273cb378)

**Comment by ZWQ652** [comment]
![image](https://github.com/user-attachments/assets/88e28c78-97f5-4c9c-8864-75c99c03b250)
When using these two plugins, an error message "no usage" will be generated
So I tried using 'ts features default extension', but I couldn't read jsconfig. json from the in memory file system

![image](https://github.com/user-attachments/assets/0e58bfd6-deac-40fd-9e38-01c73a7838b3)
I thought there was no need for 'lsp server' based on the description above.

Sorry!

**Comment by CGNonofr** [comment]
Yes, did you read my previous comment?

**Comment by ZWQ652** [comment]
> Yes, did you read my previous comment?是的，你看到我之前的评论了吗?

Ok
