### ISSUE TITLE
Using `expandSuggestionDocs`

### ISSUE THREAD

**Issue by char0n** [CodinGame/monaco-vscode-api#51]
HI @CGNonofr,

I was wondering if you could help me using this library and enabling `expandSuggestionDocs`. What this setting does is that when autocompletion is performed, the documentation is automatically displayed. 

Before using this library I've used following code to get the job done. This code still works but the `override` part with `storageService` is no longer working. Do you have any suggestion?

THanks a lot!

```js
monaco.editor.create(
      containerRef.current,
      {
        value,
        language,
        // semantic tokens provider is disabled by default; https://github.com/microsoft/monaco-editor/issues/1833
        'semanticHighlighting.enabled': true,
        theme,
        glyphMargin: true,
        lightbulb: {
          enabled: true,
        },
        lineNumbers: 'on',
        autoIndent: 'full',
        formatOnPaste: true,
        formatOnType: true,
        wordWrap: 'on',
        minimap: {
          enabled: true,
        },
        domReadOnly: isReadOnly,
        readOnly: isReadOnly,
        wordBasedSuggestions: false,
        quickSuggestions: true,
        quickSuggestionsDelay: 300,
        fixedOverflowWidgets: true,
        'bracketPairColorization.enabled': true,
        suggest: {
          snippetsPreventQuickSuggestions: false,
        },
        renderWhitespace: true,
      },
      {
        storageService: {
          get() {},
          getBoolean(key) {
            console.dir(key);
            return key === 'expandSuggestionDocs';
          },
          getNumber() {
            return 0;
          },
          remove() {},
          store() {},
          onWillSaveState() {},
          onDidChangeStorage() {},
          onDidChangeValue() {},
        },
      }
    );
```

**Comment by CGNonofr** [comment]
Hello

Is your service even used? (is your console.log triggered?)

I just tried setting the value (`StandaloneServices.get(IStorageService).store('expandSuggestionDocs', true, 0, 0)`) and it did display the documentation by default

Note that you don't have to override the service, monaco uses a memory storage service, you can update update the value in it

**Comment by CGNonofr** [comment]
Btw, I just realized IStorageService wasn't exported, added in https://github.com/CodinGame/monaco-vscode-api/pull/52 which will come soon

**Comment by char0n** [comment]
> Hello
> 
> Is your service even used? (is your console.log triggered?)

Yep, the log is triggered.

> I just tried setting the value (`StandaloneServices.get(IStorageService).store('expandSuggestionDocs', true, 0, 0)`) and it did display the documentation by default
> 
> Note that you don't have to override the service, monaco uses a memory storage service, you can update update the value in it

Yep, it worked like a charm. Thank you!

**Comment by char0n** [comment]
> Btw, I just realized IStorageService wasn't exported, added in #52 which will come soon

Yeah, I've noticed. I've used:

```js
import { IStorageService } from 'monaco-editor/esm/vs/platform/storage/common/storage.js';
```
