### ISSUE TITLE
TypeError: Cannot set properties of undefined (setting 'vscodetextmate') when using TextMate worker

### ISSUE THREAD

**Issue by Barahlush** [CodinGame/monaco-vscode-api#519]
1) When using TextMate override service with TextMate worker, there is an error in the console:
![image](https://github.com/user-attachments/assets/24c50399-8659-4118-87fd-15018a374ab7)

2) In the same setup, code highlighting doesn't work until the code is edited in any way (e.g. adding whitespace turns the highlighting on)

Repo with setup: https://github.com/Barahlush/monaco_textmate_sample
Steps to reproduce:
```shell
bun install
bun run dev
```

OS: Mac OS Sequoia 15.0.1
Browser: Chromium 130.0.6723.59 (Arc Browser)

OS: Windows 10
Browser: Microsoft Edge 130.0.2849.46 (also Chromium)

**Comment by CGNonofr** [comment]
Thank you for the short detailed report, I'll have a look

**Comment by CGNonofr** [comment]
Just had a look. It's more of a vite issue that a monaco-vscode-api issue.

Some dependencies are still using commonjs, and vite, in dev mode, doesn't seem to try and transform them

you need to force him to do so by adding:

```typescript
  optimizeDeps: {
    include: [
      "vscode-textmate",
      "vscode-oniguruma"
    ],
  },
```

in the vite config

**Comment by Barahlush** [comment]
That works, thanks!
