### ISSUE TITLE
Demo: Console error on "Close All"

### ISSUE THREAD

**Issue by kaisalmen** [CodinGame/monaco-vscode-api#524]
I see this error in the console, when I use "Close All" in the demo (locally and the deployed version):
![image](https://github.com/user-attachments/assets/adac2bca-bca0-457d-b14c-ece0e5142926)

**Comment by kaisalmen** [comment]
Ok, thanks for the explanation. Then this is not an issue.

**Comment by CGNonofr** [comment]
It probably is, but that problem is at a lost of places in the VSCode codebase and there don't use eslint rules to prevent it so...
