### ISSUE TITLE
Diagnostics to IMarkerData

### ISSUE THREAD

**Issue by char0n** [CodinGame/monaco-vscode-api#53]
I was wondering if there is a way (within API of this library) to achieve transformation from `Diagnostics` to `IMarkerData`. Basically the same transformation as `monaco-languageclient` provided here: https://github.com/TypeFox/monaco-languageclient/blob/d43ff7971dd0fbb25f3eb6603a1b57c6159b3604/packages/client/src/monaco-converter.ts#L1002

Thanks for any answer!

**Comment by CGNonofr** [comment]
Not directly, I think the closer you can get is to set a model diagnostics using
```typescript
vscode.languages.createDiagnosticCollection('customCollection').set(uri, diagnostics)
```
then get the markers:

```typescript
monaco.editor.getModelMarkers({ owner: 'customCollection', resource: uri })
```

What is your use-case exactly?

**Comment by char0n** [comment]
My use-case is validation. I get `Diagnostics` from the worker and need to set them to monaco.

What we were doing before, was to get `Diagnostics` from worker, them use `monaco-converter` from `monaco-languageclient` to transform it to `IMarkerData` and then we set to monaco via `monaco.editor.setMarkerData`.

It seems that what is sufficient now (as you pointed out) is to create the diagnostics collection and set data on it. It will automatically propagate to  monaco.

```js
vscode.languages.createDiagnosticCollection('customCollection').set(uri, diagnostics)
```

**Comment by char0n** [comment]
Here is a code of the adapter I'm trying to implement: https://github.com/swagger-api/swagger-editor/blob/1a3a124d300b90d99fb5234da1828f2e8e1e7ed3/src/plugins/editor-monaco/workers/apidom/adapters/DiagnosticsAdapter.js

It comes from this PR: https://github.com/swagger-api/swagger-editor/pull/3479

**Comment by CGNonofr** [comment]
Btw, is there a reason you don't use LSP over web worker but reimplement it by hands?

**Comment by char0n** [comment]
The code was there before I came around, I'm trying to refactor it now and make it simpler and more standard. 

As I understand the code or worker was implemented to minic https://github.com/microsoft/monaco-editor/blob/main/src/language/typescript/tsWorker.ts.

Do you have any suggestion how to code could be simplified?

**Comment by CGNonofr** [comment]
Another way is to create a worker that follows the language server protocol through `postMessage`s and use `monaco-languageclient` (there is a demo of that in the repo) but I've never used it myself

**Comment by char0n** [comment]
> Another way is to create a worker that follows the language server protocol through `postMessage`s and use `monaco-languageclient` (there is a demo of that in the repo) but I've never used it myself

I've looked at https://github.com/TypeFox/monaco-languageclient/blob/main/packages/examples/client/src/client.ts and thought about what you proposed in last comment. Sounds like I would have to pull in additional library `monaco-languageclient` (which I managed to get rid of during last couple of days) and I'm still failing to understand what the benefit from doing what you proposing would be. The current architecture is exactly the same as monaco-editor has in it's languages: https://github.com/microsoft/monaco-editor/tree/main/src/language

If we change the architecture to something different, there needs to be some added benefit to it.

**Comment by CGNonofr** [comment]
The example I'm referring to is https://github.com/TypeFox/monaco-languageclient/tree/main/packages/examples/browser-lsp

I see your are using https://github.com/swagger-api/apidom/tree/main/packages/apidom-ls which says:

> ApiDOM Language Service APIs adhere to [LSP Protocol](https://microsoft.github.io/language-server-protocol/) and are therefore usable via a LSP Server wrapper in a variety of editors and IDEs.

So I guess there is a way to start it in a worker and just plug it on monaco-languageclient with very little code

**Comment by char0n** [comment]
@CGNonofr I'll try to experiment with it, but feel free to issue PR about what you have in mind yourself.

**Comment by char0n** [comment]
@CGNonofr after some research I know understand what you meant: Language Server running in webworker and monaco-languageclient pulling data out of it right. We've created epic and issues around it. Thanks for pointing this out.

Closing this issue as the original topic of this issue has been resolved.
