### ISSUE TITLE
where to get tmLanguage and language configuration files

### ISSUE THREAD

**Issue by souporserious** [CodinGame/monaco-vscode-api#80]
First, thank you so much for this library and the other libraries you maintain for Monaco! I'm trying to set up a simple TypeScript editor in Next.js with TextMate support and wondering where to get the tmLanguage and language configuration files?

**Comment by CGNonofr** [comment]
Hello, you can get them from https://github.com/microsoft/vscode/tree/main/extensions/typescript-basics

**Comment by souporserious** [comment]
Wonderful, thank you!

**Comment by souporserious** [comment]
@CGNonofr do you happen to know why I'd be getting this error when calling `setGrammars`?

<img width="661" alt="image" src="https://user-images.githubusercontent.com/2762082/226155703-58041538-e2a5-408c-87f4-5b30cbecc3e7.png">

This is what I'm trying to do, full example [here](https://github.com/souporserious/next-monaco/blob/main/next-monaco/editor/setup.ts#L98):

```ts
setGrammars(
  [
    {
      language: 'typescript',
      scopeName: 'source.ts',
      path: './typescript.tmLanguage.json',
    },
    {
      language: 'typescriptreact',
      scopeName: 'source.tsx',
      path: './typescriptreact.tmLanguage.json',
    },
  ],
  async (grammar) => {
    switch (grammar.scopeName) {
      case 'source.ts':
        return (await import('./TypeScript.tmLanguage.json')).default as any
      case 'source.tsx':
        return (await import('./TypeScriptReact.tmLanguage.json'))
          .default as any
    }
    throw new Error('grammar not found')
  }
)
```

**Comment by CGNonofr** [comment]
You need to set the languages first by using `setLanguages`

Take a look at https://github.com/CodinGame/monaco-vscode-api/blob/main/demo/src/setup.ts

**Comment by souporserious** [comment]
Hm, I forked that file and am doing that above here like [this](https://github.com/souporserious/next-monaco/blob/main/next-monaco/editor/setup.ts#L84):

```ts
setLanguages([
  {
    id: 'typescript',
    extensions: ['.ts', '.tsx'],
    aliases: ['TypeScript', 'ts', 'typescript'],
    configuration: './typescript-configuration',
  },
])
```

Maybe I missed something else since there isn't any highlighting that's applied and the callback to `setGrammars` is never called.

**Comment by CGNonofr** [comment]
Ok sorry I didn't go to see your example.

I don't know about the typescript language but the typescriptreact language is missing for sure, maybe it's linked

**Comment by souporserious** [comment]
No worries! Yeah, not really sure what's going on. Even if I just try to load a TypeScript version without any of the React portion it still throws that error in the console.

**Comment by CGNonofr** [comment]
I've just tried taking your files (grammar+config) and adding the language/grammar registration into the demo here and everything seems fine. Please provide a simple project that reproduces it

**Comment by souporserious** [comment]
Weird, I wonder if there was something in the monorepo causing that. I made a [minimal repo here](https://github.com/souporserious/next-monaco-vscode-api) with a simple Next app that showcases a new issue with the configuration file not loading even though it's being loaded through `setLanguageConfiguration`. Also, do I need to load `TypeScriptReact` grammar? Hoping to at least get TypeScript working first and then I can look into React. I really appreciate all of your help so far! I'm pretty lost on most of this and just looking to get textmate grammar highlighting 😄

**Comment by CGNonofr** [comment]
I don't have the same error as you on your repo, but I have others
- missing `.json` on the language configuration
- the webpack worker loader was transforming some monaco internal files
- You were not setting the theme after installing it
- The worker wasn't configured to allow jsx syntax

here's the patch that makes it work: [fix.zip](https://github.com/CodinGame/monaco-vscode-api/files/11021376/fix.zip)

**Comment by souporserious** [comment]
Woot, THANK YOU SO MUCH! This is working perfectly now 🎉 again, greatly appreciate all of your help! 🙏

**Comment by souporserious** [comment]
Hello again, I tried upgrading recently to the latest monaco-vscode-api version and I'm running into issues again trying to get syntax highlighting working properly 😞. I'm not entirely sure what's going, but I tried following the recent changes to the demo in my PR [here](https://github.com/souporserious/next-monaco/pull/1/files#diff-182c1fec4e17fa4f0e89321eff03ecd3a4dd26db98661c9471982e0d64f1256d), but it just renders an editor with no theme. It looks like none of the files ever try to load so assuming it may be some configuration I'm missing in the new API.

**Comment by CGNonofr** [comment]
Ok there is a bug: if you don't use the vscode api, the extensions are not loaded

Use any vscode api and it'll work, the bug will be fixed in the next release

for instance:
```typescript
import * as vscode from 'vscode'

vscode.languages.registerColorProvider('java', {
  provideColorPresentations() {
    return []
  },
  provideDocumentColors: function (document: vscode.TextDocument, token: vscode.CancellationToken): vscode.ProviderResult<vscode.ColorInformation[]> {
    return []
  }
})
```

You have also an issue with the oniguruma wasm loading, you must add `assetPrefix: 'http://localhost:3000/',` in your next config

**Comment by souporserious** [comment]
Ah ok good to know, thank you, that looks like it fixed it! 🙏  Is there any way to load oniguruma in this new configuration without needing to provide a specific asset prefix like previously? If possible, I'd like to automate this for the end user. I could potentially read the package json and see if they have set a custom port, but then I'd also need to know the production url 🤔

**Comment by CGNonofr** [comment]
Not anymore, it's related to the way vscode is loading assets
