### ISSUE TITLE
Asset handling should be end user firendly

### ISSUE THREAD

**Issue by kaisalmen** [CodinGame/monaco-vscode-api#85]
@CGNonofr I guess it makes sense to open an issue here to discuss possible ways forward.

Ideally, end-users of `monaco-vscode-api` will not notice that assets like wasm, mp3, etc are required to be handled/loaded.

If this cannot be achieved there should be a common way to override fetch instructions (e.g. a config function that allows to provide an object with fetch override instructions). If this is not used the default settings are used.

**Comment by CGNonofr** [comment]
monaco-editor already expects the end user to load ttf files as URL I think so we're just introducing the same thing for mp3 and wasm

**Comment by kaisalmen** [comment]
Yes, I guess code transformation process needs to integrate "hook" code where resources are loaded where you can configure the urls.

For example (idea) if nothing is provided the defaults are used:
```typescript
StandaloneServices.globalSettings({
  basePath: '..',
  onigWasmPath: './node_module/svscode-onigurum/release/',
  mp3Path: '../mps3s'
});
```
Questions are? Is this feasible? Are there already global settings available one could re-use/extend?

**Comment by kaisalmen** [comment]
> Some bundlers support it by configuration (vite supports the ?url query string, with webpack you can use the file-loader! prefix ; probably deprecated) but it's not standard.

I currently don't know a way how to tell vite or webpack (monaco-languageclient) how to resolve the cors problem. Do you know a solution to this problem? Why is this problem not occur in the demo here?

I was wondering if the approach `getWorker` from `monaco-editor` could be a blueprint?

**Comment by kaisalmen** [comment]
> A cors problem? I'm not sure what you are talking about

I was referring to this problem: https://github.com/TypeFox/monaco-languageclient/pull/470#issuecomment-1480783505

**Comment by CGNonofr** [comment]
Ok that's not a Cors issue at all. You got this error because by default vite return the file:// url when loading an asset in dev mode, it works when using it on <img> tags or other things but vscode does a `fetch` by hands on it and it fails. The solution is to add the server.origin in the vite config

**Comment by kaisalmen** [comment]
> The solution is to add the server.origin in the vite config

Thank you. This works. How did you know this was actually the problem? I wasn't able to derive this from the error. Did you encounter this problem before? Oh, I just check the demo and saw that you set `origin: 'http://localhost:5173'`. I overlooked that one before.

**Comment by CGNonofr** [comment]
> Thank you. This works. How did you know this was actually the problem?

I've dug into the code to implement the require.toUri stuff and I had the problem at first

**Comment by kaisalmen** [comment]
@CGNonofr I will close this now. If I stumble upon anything related I will open specific issues/PRs.
