### ISSUE TITLE
Should extension contributes.keybindings work

### ISSUE THREAD

**Issue by kaisalmen** [CodinGame/monaco-vscode-api#87]
@CGNonofr when I directly set `keybindings` in the `contributes` section of the object that I pass to `registerExtension(extension)` I get the following error. Is this expected behaviour, because it is not supported? Setting it with `updateUserKeybindings` works:
![image](https://user-images.githubusercontent.com/21079138/229737139-7c1b9bea-c426-4d14-afb3-4fcc970458d7.png)

**Comment by CGNonofr** [comment]
Well spotted, I didn't use that part so I didn't test it

here's the fix: https://github.com/CodinGame/monaco-vscode-api/pull/88

btw, the configuration and configurationDefault extensions point are not handled, it'll come soon in another PR

**Comment by kaisalmen** [comment]
Sounds great
