### ISSUE TITLE
Disabling Notifications

### ISSUE THREAD

**Issue by aram0112** [CodinGame/monaco-vscode-api#89]
Hello! I was wondering if there was an easy way to disable notifications? I am repeatedly getting server errors from monaco related to my languageclient connection and this is repeatedly disabling notification toasts that I would much rather hide if possible. Thank you!

**Comment by CGNonofr** [comment]
Hello,

You can remove all notifications by just not using the notification service override

**Comment by aram0112** [comment]
Hi! Thank you for your response, the notifications seem to be appearing as I use the getMessageServiceOverride when implementing the monaco-languageclient. I see that this override is deprecated, is that my issue? If so what should I use instead?

**Comment by CGNonofr** [comment]
It was split into notification and dialog. It was kept for backward compatibility and just calls the 2 other ones

**Comment by aram0112** [comment]
Ah, I see. I imported vscode/service-override/dialogs instead of vscode/service-override/messages and the language client is working without notifications! Thank you very much!
