### ISSUE TITLE
mp3 files in latest releases

### ISSUE THREAD

**Issue by char0n** [CodinGame/monaco-vscode-api#90]
I've noticed that there is now `assets/` directory within the package that contains **mp3** files. Those files get pull into resulting build fragments.

Working on webpack@5 configuration that can get rid of those **mp3** files. It's around 900KB of binary data.

**Comment by CGNonofr** [comment]
It's only used by the audioCue service override but it's imported even if you don't use it, it's probably an issue indeed.

Btw, it expects the mp3 files to be loaded as url, so it shouldn't impact the loaded bundle size (just emit the mp3 in the output folder)

**Comment by char0n** [comment]
If somebody consumes the swagger-editor (the library that integrates this library) ESM build fragment and will build the custom version of the editor, he/she will have to deal with the **mp3** files there as well. 

Do you plan to provide the fix for this?

**Comment by CGNonofr** [comment]
I'll have a look!

**Comment by CGNonofr** [comment]
can you check the v1.76.7?

**Comment by char0n** [comment]
@CGNonofr I can confirm, the build no longer generate **.mp3** artifacts with v1.76.7

**Comment by char0n** [comment]
Thanks for the quick fix
