### ISSUE TITLE
allow configuring oniguruma url

### ISSUE THREAD

**Issue by souporserious** [CodinGame/monaco-vscode-api#95]
I upgraded to the recent version with the help of @CGNonofr, but I'm having trouble providing an out-of-the-box solution for my Next.js plugin due to the new constraint of oniguruma being loaded exclusively by vscode. I understand this isn't necessarily an issue of this library as from what I understand it's vscode's architecture now enforcing this constraint, but I was curious if this library could provide a sort of escape hatch that didn't require setting `assetPrefix` at least in Next.js applications? Right now this will break things like preview deployments since those urls are unique to each deployment. Is there a happy path here where I could provide my own hosted oniguruma URL without needing to provide the local/production url?

**Comment by CGNonofr** [comment]
Actually there is a simple way: https://github.com/CodinGame/monaco-vscode-api/pull/97

**Comment by souporserious** [comment]
Woot, glad there's a simpler approach. Thank you for looking into that so quickly! Once that's merged will it require any additional configuration or should Webpack just handle it now automatically?

**Comment by CGNonofr** [comment]
Can you confirm?

**Comment by souporserious** [comment]
Yes, just tested, and it's working great now on both local and prod! 🙌 Thank you again for the quick turnaround!
